// ** Icons Import
import {
  CheckSquare,
  FileText,
  Circle,
  ShoppingCart,
  User,
  Shield,
  Archive,
  ArrowDownCircle,
  ArrowDownLeft,
  ArrowDownRight,
  ArrowDown,
  ArrowLeftCircle,
  ArrowLeft,
  ArrowRightCircle,
  ArrowRight,
  ArrowUpCircle,
  ArrowUpLeft,
  ArrowUpRight,
  ArrowUp,
  AtSign,
  Award,
  BarChart2,
  BarChart,
  BatteryCharging,
  Battery,
  BellOff,
  Bell,
  Bluetooth,
  Bold,
  BookOpen,
  Book,
  Bookmark,
  Box,
  Briefcase,
  CameraOff,
  Camera,
  Cast,
  CheckCircle,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsDown,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUp,
  Chrome,
  Clipboard,
  Clock,
  CloudDrizzle,
  CloudLightning,
  CloudOff,
  CloudRain,
  CloudSnow,
  Cloud,
  Code,
  Codepen,
  Codesandbox,
  Coffee,
  Columns,
  Command,
  Compass,
  Copy,
  CornerDownLeft,
  CornerDownRight,
  CornerLeftDown,
  CornerLeftUp,
  CornerRightDown,
  CornerRightUp,
  CornerUpLeft,
  CornerUpRight,
  Cpu,
  CreditCard,
  Crop,
  Crosshair,
  Database,
  Delete,
  Disc,
  DivideCircle,
  DivideSquare,
  Divide,
  DollarSign,
  DownloadCloud,
  Download,
  Dribbble,
  Droplet,
  Edit2,
  Edit3,
  Edit,
  ExternalLink,
  EyeOff,
  Eye,
  Facebook,
  FastForward,
  Feather,
  Figma,
  FileMinus,
  FilePlus,
  File,
  Film,
  Filter,
  Flag,
  FolderMinus,
  FolderPlus,
  Folder,
  Framer,
  Frown,
  Gift,
  GitBranch,
  GitCommit,
  GitMerge,
  GitPullRequest,
  GitHub,
  Gitlab,
  Globe,
  Grid,
  HardDrive,
  Hash,
  Headphones,
  Heart,
  HelpCircle,
  Hexagon,
  Home,
  Image,
  Inbox,
  Info,
  Instagram,
  Italic,
  Key,
  Layers,
  Layout,
  LifeBuoy,
  Link2,
  Link,
  Linkedin,
  List,
  Loader,
  Lock,
  LogIn,
  LogOut,
  MapPin,
  Map,
  Maximize2,
  Maximize,
  Meh,
  Menu,
  MessageCircle,
  MicOff,
  Mic,
  Minimize2,
  Minimize,
  MinusCircle,
  MinusSquare,
  Minus,
  Monitor,
  Moon,
  MoreHorizontal,
  MoreVertical,
  MousePointer,
  Move,
  Music,
  Navigation2,
  Navigation,
  Octagon,
  Package,
  Paperclip,
  PauseCircle,
  Pause,
  PenTool,
  Percent,
  PhoneCall,
  PhoneForwarded,
  PhoneIncoming,
  PhoneMissed,
  PhoneOff,
  PhoneOutgoing,
  Phone,
  PieChart,
  PlayCircle,
  Play,
  PlusCircle,
  PlusSquare,
  Plus,
  Pocket,
  Power,
  Printer,
  Radio,
  RefreshCcw,
  RefreshCw,
  Repeat,
  Rewind,
  RotateCcw,
  RotateCw,
  Rss,
  Save,
  Scissors,
  Search,
  Send,
  Server,
  Settings,
  Share2,
  Share,
  ShieldOff,
  ShoppingBag,
  Shuffle,
  Sidebar,
  SkipBack,
  SkipForward,
  Slack,
  Slash,
  Sliders,
  Smartphone,
  Smile,
  Speaker,
  Square,
  Star,
  StopCircle,
  Sun,
  Sunrise,
  Sunset,
  Table,
  Tablet,
  Tag,
  Target,
  Terminal,
  Thermometer,
  ThumbsDown,
  ThumbsUp,
  ToggleLeft,
  ToggleRight,
  Tool,
  Trash2,
  Trash,
  Trello,
  TrendingDown,
  TrendingUp,
  Triangle,
  Truck,
  Tv,
  Twitch,
  Twitter,
  Type,
  Umbrella,
  Underline,
  Unlock,
  UploadCloud,
  Upload,
  UserCheck,
  UserMinus,
  UserPlus,
  UserX,
  Users,
  VideoOff,
  Video,
  Voicemail,
  Volume1,
  Volume2,
  VolumeX,
  Volume,
  Watch,
  WifiOff,
  Wifi,
  Wind,
  XCircle,
  XOctagon,
  XSquare,
  X,
  Youtube,
  ZapOff,
  Zap,
  ZoomIn,
} from "react-feather";

export default [
  {
    id: "discounts",
    title: "Discounts && Promos",
    icon: <Archive size={20} />,
    children: [
      {
        id: "monthly-discount",
        title: "Monthly Discount",
        icon: <Circle size={12} />,
        navLink: "/monthly-discount",
      },
      {
        id: "discount-request",
        title: "Discount Request",
        icon: <Circle size={12} />,
      },
      {
        id: "discount-adjustment",
        title: "Discount Adjustment",
        icon: <Circle size={12} />,
      },
      {
        id: "deactivate-discount",
        title: "Deactivate Discount",
        icon: <Circle size={12} />,
      },
      {
        id: "monthly-discount-request",
        title: "Monthly Discount Request",
        icon: <Circle size={12} />,
      },
      {
        id: "per-case-discount-request-primary",
        title: "Per Case Discount Request (Primary)",
        icon: <Circle size={12} />,
      },
      {
        id: "per-case-discount-deactivate",
        title: "Per Case Discount Deactivate",
        icon: <Circle size={12} />,
      },
      {
        id: "upfront-discount-request",
        title: "Upfront Discount Request",
        icon: <Circle size={12} />,
      },
      {
        id: "slip-printing",
        title: "Slip Printing",
        icon: <Circle size={12} />,
      },
      {
        id: "slip-dispatch",
        title: "Slip Dispatch",
        icon: <Circle size={12} />,
      },
      {
        id: "slip-receiving",
        title: "Slip Receiving",
        icon: <Circle size={12} />,
      },
      {
        id: "slip-cancellation",
        title: "Slip Cancellation",
        icon: <Circle size={12} />,
      },
      {
        id: "credit-slip",
        title: "Credit Slip",
        icon: <Circle size={12} />,
      },
      {
        id: "credit-slip-printing",
        title: "Credit Slip Printing",
        icon: <Circle size={12} />,
      },
      {
        id: "credit-slip-receiving",
        title: "Credit Slip Receiving",
        icon: <Circle size={12} />,
      },
      {
        id: "credit-slip-distributor",
        title: "Credit Slip ( Distributor )",
        icon: <Circle size={12} />,
      },
      {
        id: "credit-slip-printing-distributor",
        title: "Credit Slip Printing (Distributor)",
        icon: <Circle size={12} />,
      },
    ],
  },
];
