import {
  Regions,
  Users,
  Settings,
  DashboardIcon,
  HajjComplience,
  Forms,
  productionIcon,
  Compliance,
  lightsvg,
  pinMapIcon,
  discountIcon,
  priceIcon,
  inventoryIcon,
  saleIcon,
  mobileIcon,
  CashIcon
} from "../../assets/wasfaty/SVG";

const navigationLinks = [
  {
    id: "dashboards",
    slug: "dashboards",
    title: "Dashboards",
    icon: () => DashboardIcon,
    navLink: "/",
    // children: [
    //   {
    //     id: "order_booker",
    //     slug: "order_booker",
    //     title: "Order Booker",
    //     text: "order_booker",

    //     navLink: "/",
    //     icon: () => Users,
    //   },
    //   // {
    //   //   id: "outlet",
    //   //   slug: "outlet",
    //   //   title: "Outlet",
    //   //   text: "outlet",

    //   //   navLink: "/outlet",
    //   //   icon: () => Users,
    //   // },
    //   // {
    //   //   id: "distributors",
    //   //   slug: "distributors",
    //   //   title: "Distributors",
    //   //   text: "distributors",

    //   //   navLink: "/distributors",
    //   //   icon: () => Users,
    //   // },
    //   // {
    //   //   id: "region",
    //   //   slug: "region",
    //   //   title: "Region",
    //   //   text: "region",

    //   //   navLink: "/region",
    //   //   icon: () => Regions,
    //   // },
    // ],
  },
  {
    id: "production",
    slug: "production",
    title: "Production",
    icon: () => productionIcon,
    navLink: "/production",
    // children: [
    //   // {
    //   //   id: "grn",
    //   //   slug: "grn",
    //   //   title: "GRN",
    //   //   text: "grn",
    //   //   navLink: "/grn",
    //   // },
    //   // {
    //   //   id: "stock",
    //   //   slug: "stock",
    //   //   title: "Stock",
    //   //   text: "stock",

    //   //   navLink: "/stock",
    //   // },
    //   // {
    //   //   id: "report",
    //   //   slug: "report",
    //   //   title: "Report",
    //   //   text: "report",

    //   //   navLink: "/report",
    //   // },
    // ],
  },
  // {
  //   id: "discounts_promo",
  //   slug: "discounts_promo",
  //   title: "Discounts & Promo",
  //   icon: () => discountIcon,

  //   children: [
  //     {
  //       id: "slip",
  //       slug: "slip",
  //       title: "Slip",
  //       text: "slip",

  //       navLink: "/slip",
  //     },
  //     {
  //       id: "credit_slip",
  //       slug: "credit_slip",
  //       title: "Credit Slip",
  //       text: "credit_slip",

  //       navLink: "/credit_slip",
  //     },
  //   ],

  //   // children: [
  //   //   {
  //   //     id: "discount_request",
  //   //     slug: "discount_request",
  //   //     title: "Discount Request",
  //   //     text: "discount_request",

  //   //     navLink: "/discount_request",
  //   //     icon: () => Users,
  //   //   },
  //   //   {
  //   //     id: "monthly_discounts",
  //   //     slug: "monthly_discounts",
  //   //     title: "Monthly Discounts",
  //   //     text: "monthly_discounts",

  //   //     navLink: "/monthly_discounts",
  //   //     icon: () => Users,
  //   //   },
  //   //   {
  //   //     id: "slip_printing",
  //   //     slug: "slip_printing",
  //   //     title: "Slip Printing",
  //   //     text: "slip_printing",

  //   //     navLink: "/slip_printing",
  //   //     icon: () => Users,
  //   //   },
  //   //   {
  //   //     id: "slip_dispatch",
  //   //     slug: "slip_dispatch",
  //   //     title: "Slip Dispatch",
  //   //     text: "slip_dispatch",

  //   //     navLink: "/slip_dispatch",
  //   //     icon: () => Users,
  //   //   },
  //   //   {
  //   //     id: "slip_receiving",
  //   //     slug: "slip_receiving",
  //   //     title: "Slip Receiving",
  //   //     text: "slip_receiving",

  //   //     navLink: "/slip_receiving",
  //   //     icon: () => Users,
  //   //   },
  //   //   {
  //   //     id: "discount_adjustment",
  //   //     slug: "discount_adjustment",
  //   //     title: "Discount Adjustment",
  //   //     text: "discount_adjustment",

  //   //     navLink: "/discount_adjustment",
  //   //     icon: () => Users,
  //   //   },
  //   //   {
  //   //     id: "deactivate_discount",
  //   //     slug: "deactivate_discount",
  //   //     title: "Deactivate Discount",
  //   //     text: "deactivate_discount",

  //   //     navLink: "/deactivate_discount",
  //   //     icon: () => Users,
  //   //   },
  //   //   {
  //   //     id: "monthly_discount_request",
  //   //     slug: "monthly_discount_request",
  //   //     title: "Monthly Discount Request",
  //   //     text: "monthly_discount_request",

  //   //     navLink: "/monthly_discount_request",
  //   //     icon: () => Users,
  //   //   },
  //   //   {
  //   //     id: "slip_cancellation",
  //   //     slug: "slip_cancellation",
  //   //     title: "Slip Cancellation",
  //   //     text: "slip_cancellation",

  //   //     navLink: "/slip_cancellation",
  //   //     icon: () => Users,
  //   //   },
  //   //   {
  //   //     id: "credit_slip",
  //   //     slug: "credit_slip",
  //   //     title: "Credit Slip",
  //   //     text: "credit_slip",

  //   //     navLink: "/credit_slip",
  //   //     icon: () => Users,
  //   //   },
  //   //   {
  //   //     id: "credit_slip_printing",
  //   //     slug: "credit_slip_printing",
  //   //     title: "Credit Slip Printing",
  //   //     text: "credit_slip_printing",

  //   //     navLink: "/credit_slip_printing",
  //   //     icon: () => Users,
  //   //   },
  //   //   {
  //   //     id: "credit_slip_distributor",
  //   //     slug: "credit_slip_distributor",
  //   //     title: "Credit Slip (Distributor)",
  //   //     text: "credit_slip_distributor",

  //   //     navLink: "/credit_slip_distributor",
  //   //     icon: () => Users,
  //   //   },
  //   //   {
  //   //     id: "credit_slip_printing_distributor",
  //   //     slug: "credit_slip_printing_distributor",
  //   //     title: "Credit Slip Printing (Distributor)",
  //   //     text: "credit_slip_printing_distributor",

  //   //     navLink: "/credit_slip_printing_distributor",
  //   //     icon: () => Users,
  //   //   },
  //   //   {
  //   //     id: "planned_sales",
  //   //     slug: "planned_sales",
  //   //     title: "Planned Sales",
  //   //     text: "planned_sales",

  //   //     navLink: "/planned_sales",
  //   //     icon: () => Users,
  //   //   },
  //   //   {
  //   //     id: "per_case_discount_request_primary",
  //   //     slug: "per_case_discount_request_primary",
  //   //     title: "Per Case Discount Request (Primary)",
  //   //     text: "per_case_discount_request_primary",

  //   //     navLink: "/per_case_discount_request_primary",
  //   //     icon: () => Users,
  //   //   },
  //   //   {
  //   //     id: "per_case_discount_deactivate",
  //   //     slug: "per_case_discount_deactivate",
  //   //     title: "Per Case Discount Deactivate",
  //   //     text: "per_case_discount_deactivate",

  //   //     navLink: "/per_case_discount_deactivate",
  //   //     icon: () => Users,
  //   //   },
  //   //   {
  //   //     id: "upfront_discount_request",
  //   //     slug: "upfront_discount_request",
  //   //     title: "Upfront Discount Request",
  //   //     text: "upfront_discount_request",

  //   //     navLink: "/upfront_discount_request",
  //   //     icon: () => Users,
  //   //   },
  //   //   {
  //   //     id: "primary_promotion_deactivation",
  //   //     slug: "primary_promotion_deactivation",
  //   //     title: "Primary Promotion Deactivation",
  //   //     text: "primary_promotion_deactivation",

  //   //     navLink: "/primary_promotion_deactivation",
  //   //     icon: () => Users,
  //   //   },
  //   // ],
  // },
  {
    id: "administration",
    slug: "administration",
    title: "Administration",
    navLink: "/new_outlet_request",
    icon: () => Users,
    // children: [
    //   {
    //     id: "new_outlet_request",
    //     slug: "new_outlet_request",
    //     title: "New Outlet Request",
    //     // text: "User",
    //     navLink: "/new_outlet_request",
    //     icon: () => Users,
    //   },
    // ],

    // children: [
    //   {
    //     id: "new_outlet_request",
    //     slug: "new_outlet_request",
    //     title: "New Outlet Request",
    //     // text: "User",
    //     navLink: "/new_outlet_request",
    //     icon: () => Users,
    //   },
    //   {
    //     id: "userRights",
    //     slug: "UserRights",
    //     title: "User Rights",
    //     // text: "User",
    //     navLink: "/UserRights",
    //     icon: () => Users,
    //   },
    //   {
    //     id: "distributorGroups",
    //     slug: "DistributorGroups",
    //     title: "Distributor Groups",
    //     // text: "User",
    //     navLink: "/DistributorGroups",
    //     icon: () => Users,
    //   },
    //   {
    //     id: "productGroups",
    //     slug: "ProductGroups",
    //     title: "Product Groups",
    //     // text: "User",
    //     navLink: "/ProductGroups",
    //     icon: () => Users,
    //   },
    //   {
    //     id: "employeeHierarchy",
    //     slug: "EmployeeHierarchy",
    //     title: "Employee Hierarchy",
    //     // text: "User",
    //     navLink: "/EmployeeHierarchy",
    //     icon: () => Users,
    //   },
    //   {
    //     id: "employeeHierarchyAll",
    //     slug: "EmployeeHierarchyAll",
    //     title: "Employee Hierarchy [All]",
    //     // text: "User",
    //     navLink: "/EmployeeHierarchyAll",
    //     icon: () => Users,
    //   },
    //   {
    //     id: "employeeHierarchyLimited",
    //     slug: "EmployeeHierarchyLimited",
    //     title: "Employee Hierarchy [Limited]",
    //     // text: "User",
    //     navLink: "/EmployeeHierarchyLimited",
    //     icon: () => Users,
    //   },
    //   {
    //     id: "distributors",
    //     slug: "Distributors",
    //     title: "Distributors",
    //     // text: "User",
    //     navLink: "/Distributors",
    //     icon: () => Users,
    //   },
    //   {
    //     id: "manageDistributors",
    //     slug: "ManageDistributors",
    //     title: "Manage Distributors",
    //     // text: "User",
    //     navLink: "/ManageDistributors",
    //     icon: () => Users,
    //   },
    //   {
    //     id: "productPromotions",
    //     slug: "ProductPromotions",
    //     title: "Product Promotions",
    //     // text: "User",
    //     navLink: "/ProductPromotions",
    //     icon: () => Users,
    //   },
    //   {
    //     id: "distributorEmployees",
    //     slug: "DistributorEmployees",
    //     title: "Distributor Employees",
    //     // text: "User",
    //     navLink: "/DistributorEmployees",
    //     icon: () => Users,
    //   },
    //   {
    //     id: "distributorVehicles",
    //     slug: "DistributorVehicles",
    //     title: "Distributor Vehicles",
    //     // text: "User",
    //     navLink: "/DistributorVehicles",
    //     icon: () => Users,
    //   },
    //   {
    //     id: "orderBookerSetup",
    //     slug: "OrderBookerSetup",
    //     title: "Order Booker Setup",
    //     // text: "User",
    //     navLink: "/OrderBookerSetup",
    //     icon: () => Users,
    //   },
    //   {
    //     id: "outlets",
    //     slug: "Outlets",
    //     title: "Outlets",
    //     // text: "User",
    //     navLink: "/Outlets",
    //     icon: () => Users,
    //   },
    //   {
    //     id: "synchronization",
    //     slug: "Synchronization",
    //     title: "Synchronization",
    //     // text: "User",
    //     navLink: "/Synchronization",
    //     icon: () => Users,
    //   },
    //   {
    //     id: "pjpManagement",
    //     slug: "PJPManagement",
    //     title: "PJP Management",
    //     // text: "User",
    //     navLink: "/PJPManagement",
    //     icon: () => Users,
    //   },
    //   {
    //     id: "distributorTargets",
    //     slug: "DistributorTargets",
    //     title: "Distributor Targets",
    //     // text: "User",
    //     navLink: "/DistributorTargets",
    //     icon: () => Users,
    //   },
    //   {
    //     id: "mobileDevices",
    //     slug: "MobileDevices",
    //     title: "Mobile Devices",
    //     // text: "User",
    //     navLink: "/MobileDevices",
    //     icon: () => Users,
    //   },
    //   {
    //     id: "urduDictionary",
    //     slug: "UrduDictionary",
    //     title: "Urdu Dictionary",
    //     // text: "User",
    //     navLink: "/UrduDictionary",
    //     icon: () => Users,
    //   },
    //   {
    //     id: "userRightsDelegation",
    //     slug: "UserRightsDelegation",
    //     title: "User Rights Delegation",
    //     // text: "User",
    //     navLink: "/UserRightsDelegation",
    //     icon: () => Users,
    //   },
    //   {
    //     id: "userChromeActivation",
    //     slug: "UserChromeActivation",
    //     title: "User Chrome Activation",
    //     // text: "User",
    //     navLink: "/UserChromeActivation",
    //     icon: () => Users,
    //   },
    //   {
    //     id: "userAdministration",
    //     slug: "UserAdministration",
    //     title: "User Administration",
    //     // text: "User",
    //     navLink: "/UserAdministration",
    //     icon: () => Users,
    //   },
    //   {
    //     id: "priceList",
    //     slug: "PriceList",
    //     title: "Price List",
    //     // text: "User",
    //     navLink: "/PriceList",
    //     icon: () => Users,
    //   },
    //   {
    //     id: "promotionRequest",
    //     slug: "PromotionRequest",
    //     title: "Promotion Request",
    //     // text: "User",
    //     navLink: "/PromotionRequest",
    //     icon: () => Users,
    //   },
    //   {
    //     id: "productVariableCost",
    //     slug: "ProductVariableCost",
    //     title: "Product Variable Cost",
    //     // text: "User",
    //     navLink: "/ProductVariableCost",
    //     icon: () => Users,
    //   },
    //   {
    //     id: "distributorAreaAllocation",
    //     slug: "DistributorAreaAllocation",
    //     title: "Distributor Area Allocation",
    //     // text: "User",
    //     navLink: "/DistributorAreaAllocation",
    //     icon: () => Users,
    //   },
    //   {
    //     id: "outsourcingSalesDeletePermission",
    //     slug: "OutsourcingSalesDeletePermission",
    //     title: "Outsourcing Sales [Delete Permission]",
    //     // text: "User",
    //     navLink: "/OutsourcingSalesDeletePermission",
    //     icon: () => Users,
    //   },

    //   {
    //     id: "distributorPortalAddUser",
    //     slug: "DistributorPortalAddUser",
    //     title: "Distributor Portal Add User",
    //     // text: "User",
    //     navLink: "/DistributorPortalAddUser",
    //     icon: () => Users,
    //   },
    //   {
    //     id: "employeeHierarchyAdministration",
    //     slug: "EmployeeHierarchyAdministration",
    //     title: "Employee Hierarchy Administration",
    //     // text: "User",
    //     navLink: "/EmployeeHierarchyAdministration",
    //     icon: () => Users,
    //   },
    //   {
    //     id: "registerDeviceBarcode",
    //     slug: "RegisterDeviceBarcode",
    //     title: "Register Device Barcode",
    //     // text: "User",
    //     navLink: "/RegisterDeviceBarcode",
    //     icon: () => Users,
    //   },
    //   {
    //     id: "newOutletRequestCentralized",
    //     slug: "NewOutletRequestCentralized",
    //     title: "New Outlet Request Centralized",
    //     // text: "User",
    //     navLink: "/NewOutletRequestCentralized",
    //     icon: () => Users,
    //   },
    //   {
    //     id: "addGazettedHoliday",
    //     slug: "AddGazettedHoliday",
    //     title: "Add Gazetted Holiday",
    //     // text: "User",
    //     navLink: "/AddGazettedHoliday",
    //     icon: () => Users,
    //   },
    //   {
    //     id: "addDistributorLocation",
    //     slug: "AddDistributorLocation",
    //     title: "Add Distributor Location",
    //     // text: "User",
    //     navLink: "/AddDistributorLocation",
    //     icon: () => Users,
    //   },
    //   {
    //     id: "distributorPrimaryVehicles",
    //     slug: "DistributorPrimaryVehicles",
    //     title: "Distributor Primary Vehicles",
    //     // text: "User",
    //     navLink: "/DistributorPrimaryVehicles",
    //     icon: () => Users,
    //   },
    //   {
    //     id: "allowSkipMerchandising",
    //     slug: "AllowSkipMerchandising",
    //     title: "Allow Skip Merchandising",
    //     // text: "User",
    //     navLink: "/AllowSkipMerchandising",
    //     icon: () => Users,
    //   },
    //   {
    //     id: "distributorVehiclesOpening",
    //     slug: "DistributorVehiclesOpening",
    //     title: "Distributor Vehicles Opening",
    //     // text: "User",
    //     navLink: "/DistributorVehiclesOpening",
    //     icon: () => Users,
    //   },
    //   {
    //     id: "attendanceFeature",
    //     slug: "AttendanceFeature",
    //     title: "Attendance Feature",
    //     // text: "User",
    //     navLink: "/AttendanceFeature",
    //     icon: () => Users,
    //   },
    //   {
    //     id: "dispatchReturnsLiquid",
    //     slug: "DispatchReturnsLiquid",
    //     title: "Dispatch Returns [Liquid]",
    //     // text: "User",
    //     navLink: "/DispatchReturnsLiquid",
    //     icon: () => Users,
    //   },
    //   {
    //     id: "dispatchReturnsEmpty",
    //     slug: "DispatchReturnsEmpty",
    //     title: "Dispatch Returns [Empty]",
    //     // text: "User",
    //     navLink: "/DispatchReturnsEmpty",
    //     icon: () => Users,
    //   },
    //   {
    //     id: "dispatchAdjustment",
    //     slug: "DispatchAdjustment",
    //     title: "Dispatch Adjustment",
    //     // text: "User",
    //     navLink: "/DispatchAdjustment",
    //     icon: () => Users,
    //   },
    //   {
    //     id: "pjpUploader",
    //     slug: "PJPUploader",
    //     title: "PJP Uploader",
    //     // text: "User",
    //     navLink: "/PJPUploader",
    //     icon: () => Users,
    //   },
    //   {
    //     id: "downloadAllPJPs",
    //     slug: "DownloadAllPJPs",
    //     title: "Download All PJPs",
    //     // text: "User",
    //     navLink: "/DownloadAllPJPs",
    //     icon: () => Users,
    //   },
    //   {
    //     id: "reportCenter",
    //     slug: "ReportCenter",
    //     title: "Report Center",
    //     // text: "User",
    //     navLink: "/ReportCenter",
    //     icon: () => Users,
    //   },
    //   {
    //     id: "vehicleTracker",
    //     slug: "VehicleTracker",
    //     title: "Vehicle Tracker",
    //     // text: "User",
    //     navLink: "/VehicleTracker",
    //     icon: () => Users,
    //   },
    // ],
  },
  {
    id: "targets",
    slug: "targets",
    title: "Targets",
    icon: () => Forms,
    navLink: "/targets",
    // children: [
    //   {
    //     id: "psr_targets_upload",
    //     slug: "psr_targets_upload",
    //     title: "PSR Targets Upload",
    //     text: "psr_targets_upload",
    //     navLink: "/psr_targets_upload",
    //     icon: () => Settings,
    //   },
    //   {
    //     id: "distributor_targets_upload",
    //     slug: "distributor_targets_upload",
    //     title: "Distributor Targets Upload",
    //     text: "distributor_targets_upload",
    //     navLink: "/distributor_targets_upload",
    //     icon: () => Settings,
    //   },
    //   {
    //     id: "order_booker_targets",
    //     slug: "order_booker_targets",
    //     title: "Order Booker Targets",
    //     text: "order_booker_targets",
    //     navLink: "/order_booker_targets",
    //     icon: () => Settings,
    //   },
    // ],
  },
  {
    id: "price_list",
    slug: "price_list",
    title: "Price List",
    icon: () => priceIcon,
    navLink: "/price_list",

    // children: [
    //   {
    //     id: "price_list_exclude",
    //     slug: "price_list_exclude",
    //     title: "Price list Exclude",
    //     text: "price_list_exclude",
    //     navLink: "/price_list_exclude",
    //     icon: () => Settings,
    //   },
    //   {
    //     id: "base_price_list",
    //     slug: "base_price_list",
    //     title: "Base Price List",
    //     text: "base_price_list",
    //     navLink: "/base_price_list",
    //     icon: () => Settings,
    //   },
    //   {
    //     id: "ntp_daily_brand_sku_row_wise",
    //     slug: "ntp_daily_brand_sku_row_wise",
    //     title: "NTP Daily Brand SKU Row Wise",
    //     text: "ntp_daily_brand_sku_row_wise",
    //     navLink: "/ntp_daily_brand_sku_row_wise",
    //     icon: () => Settings,
    //   },
    // ],
  },
  {
    id: "supply_chain",
    slug: "supply_chain",
    title: "Supply Chain",
    icon: () => Compliance,
    navLink: "/supply_chain",

    // children: [
    //   {
    //     id: "delivery_note",
    //     slug: "delivery_note",
    //     title: "Delivery Note",
    //     text: "delivery_note",
    //     navLink: "/delivery_note",
    //   },
    //   {
    //     id: "gatepass",
    //     slug: "gatepass",
    //     title: "Gatepass",
    //     text: "gatepass",
    //     navLink: "/gatepass",
    //   },
    //   {
    //     id: "delivery_note_delete_permission",
    //     slug: "delivery_note_delete_permission",
    //     title: "Delivery Note [Delete Permission]",
    //     text: "delivery_note_delete_permission",
    //     navLink: "/delivery_note_delete_permission",
    //   },
    //   {
    //     id: "grn_distributor",
    //     slug: "grn_distributor",
    //     title: "GRN (Distributor)",
    //     text: "grn_distributor",
    //     navLink: "/grn_distributor",
    //   },
    //   {
    //     id: "lifting_report",
    //     slug: "lifting_report",
    //     title: "Lifting Report",
    //     text: "lifting_report",
    //     navLink: "/lifting_report",
    //   },
    //   {
    //     id: "lifting_report_invoice_value",
    //     slug: "lifting_report_invoice_value",
    //     title: "Lifting Report [Invoice Value]",
    //     text: "lifting_report_invoice_value",
    //     navLink: "/lifting_report_invoice_value",
    //   },
    //   {
    //     id: "delivery_report",
    //     slug: "delivery_report",
    //     title: "Delivery Report",
    //     text: "delivery_report",
    //     navLink: "/delivery_report",
    //   },
    //   {
    //     id: "draft_out_load",
    //     slug: "draft_out_load",
    //     title: "Draft Out Load",
    //     text: "draft_out_load",
    //     navLink: "/draft_out_load",
    //   },
    //   {
    //     id: "delivery_note_advance",
    //     slug: "delivery_note_advance",
    //     title: "Delivery Note Advance",
    //     text: "delivery_note_advance",
    //     navLink: "/delivery_note_advance",
    //   },
    //   {
    //     id: "transfer_note",
    //     slug: "transfer_note",
    //     title: "Transfer Note",
    //     text: "transfer_note",
    //     navLink: "/transfer_note",
    //   },
    // ],
  },
  {
    id: "inventory",
    slug: "inventory",
    title: "Inventory",
    icon: () => inventoryIcon,
    navLink: "/inventory",

    // children: [
    //   {
    //     id: "damaged_stock",
    //     slug: "damaged_stock",
    //     title: "Damaged Stock",
    //     text: "damaged_stock",
    //     navLink: "/damaged_stock",
    //   },
    //   {
    //     id: "brand_exchange",
    //     slug: "brand_exchange",
    //     title: "Brand Exchange",
    //     text: "brand_exchange",
    //     navLink: "/brand_exchange",
    //   },
    //   {
    //     id: "physical_stock_adjustment",
    //     slug: "physical_stock_adjustment",
    //     title: "Physical Stock Adjustment",
    //     text: "physical_stock_adjustment",
    //     navLink: "/physical_stock_adjustment",
    //   },
    //   {
    //     id: "unpost_delivery_note",
    //     slug: "unpost_delivery_note",
    //     title: "Unpost Delivery Note",
    //     text: "unpost_delivery_note",
    //     navLink: "/unpost_delivery_note",
    //   },
    // ],
  },
  {
    id: "sales",
    slug: "sales",
    title: "Sales",
    icon: () => saleIcon,
    navLink: "/sales",

    // children: [
    //   {
    //     id: "desk_sales",
    //     slug: "desk_sales",
    //     title: "Desk Sales",
    //     text: "desk_sales",
    //     navLink: "/desk_sales",
    //   },
    //   {
    //     id: "order_invoicing_edit",
    //     slug: "order_invoicing_edit",
    //     title: "Order Invoicing [Edit]",
    //     text: "order_invoicing_edit",
    //     navLink: "/order_invoicing_edit",
    //   },
    //   {
    //     id: "order_invoicing",
    //     slug: "order_invoicing",
    //     title: "Order Invoicing",
    //     text: "order_invoicing",
    //     navLink: "/order_invoicing",
    //   },
    //   {
    //     id: "dispatch",
    //     slug: "dispatch",
    //     title: "Dispatch",
    //     text: "dispatch",
    //     navLink: "/dispatch",
    //   },
    //   {
    //     id: "dispatch_extra_loading",
    //     slug: "dispatch_extra_loading",
    //     title: "Dispatch Extra Loading",
    //     text: "dispatch_extra_loading",
    //     navLink: "/dispatch_extra_loading",
    //   },
    //   {
    //     id: "extra_load_adjustment",
    //     slug: "extra_load_adjustment",
    //     title: "Extra Load Adjustment",
    //     text: "extra_load_adjustment",
    //     navLink: "/extra_load_adjustment",
    //   },
    //   {
    //     id: "dispatch_printing",
    //     slug: "dispatch_printing",
    //     title: "Dispatch Printing",
    //     text: "dispatch_printing",
    //     navLink: "/dispatch_printing",
    //   },
    //   {
    //     id: "dispatch_returns",
    //     slug: "dispatch_returns",
    //     title: "Dispatch Returns",
    //     text: "dispatch_returns",
    //     navLink: "/dispatch_returns",
    //   },
    //   {
    //     id: "dispatch_returns_liquid",
    //     slug: "dispatch_returns_liquid",
    //     title: "Dispatch Returns [Liquid]",
    //     text: "dispatch_returns_liquid",
    //     navLink: "/dispatch_returns_liquid",
    //   },
    //   {
    //     id: "dispatch_returns_empty",
    //     slug: "dispatch_returns_empty",
    //     title: "Dispatch Returns [Empty]",
    //     text: "dispatch_returns_empty",
    //     navLink: "/dispatch_returns_empty",
    //   },
    //   {
    //     id: "dispatch_adjustment",
    //     slug: "dispatch_adjustment",
    //     title: "Dispatch Adjustment",
    //     text: "dispatch_adjustment",
    //     navLink: "/dispatch_adjustment",
    //   },
    // ],
  },
  {
    id: "report_center",
    slug: "report_center",
    title: "Report Center",
    icon: () => lightsvg,
    navLink: "/report_center",

    // children: [
    //   {
    //     id: "r101_sales_summary",
    //     slug: "r101_sales_summary",
    //     title: "R101 - Sales Summary",
    //     text: "r101_sales_summary",
    //     navLink: "/r101_sales_summary",
    //   },
    //   {
    //     id: "r104_promotions_summary",
    //     slug: "r104_promotions_summary",
    //     title: "R104 - Promotions Summary",
    //     text: "r104_promotions_summary",
    //     navLink: "/r104_promotions_summary",
    //   },
    //   {
    //     id: "r105_promotions_package_distributor",
    //     slug: "r105_promotions_package_distributor",
    //     title: "R105 - Promotions / Package and Distributor",
    //     text: "r105_promotions_package_distributor",
    //     navLink: "/r105_promotions_package_distributor",
    //   },
    //   {
    //     id: "r106_sales_package_outlet",
    //     slug: "r106_sales_package_outlet",
    //     title: "R106 - Sales / Package and Outlet",
    //     text: "r106_sales_package_outlet",
    //     navLink: "/r106_sales_package_outlet",
    //   },
    //   {
    //     id: "r107_promotions_package_outlet",
    //     slug: "r107_promotions_package_outlet",
    //     title: "R107 - Promotions / Package and Outlet",
    //     text: "r107_promotions_package_outlet",
    //     navLink: "/r107_promotions_package_outlet",
    //   },
    //   {
    //     id: "r108_sales_package_outlet",
    //     slug: "r108_sales_package_outlet",
    //     title: "R108 - Sales / Package and Outlet",
    //     text: "r108_sales_package_outlet",
    //     navLink: "/r108_sales_package_outlet",
    //   },
    //   {
    //     id: "r109_kpi_orderbooker",
    //     slug: "r109_kpi_orderbooker",
    //     title: "R109 - KPI / Orderbooker",
    //     text: "r109_kpi_orderbooker",
    //     navLink: "/r109_kpi_orderbooker",
    //   },
    //   {
    //     id: "r111_lifting_distributor_order",
    //     slug: "r111_lifting_distributor_order",
    //     title: "R111 - Lifting / Distributor and Order",
    //     text: "r111_lifting_distributor_order",
    //     navLink: "/r111_lifting_distributor_order",
    //   },
    //   {
    //     id: "r112_order_based_sales_summary",
    //     slug: "r112_order_based_sales_summary",
    //     title: "R112 - Order based Sales Summary",
    //     text: "r112_order_based_sales_summary",
    //     navLink: "/r112_order_based_sales_summary",
    //   },
    //   {
    //     id: "r113_dispatch_based_sales_summary",
    //     slug: "r113_dispatch_based_sales_summary",
    //     title: "R113 - Dispatch based Sales Summary",
    //     text: "r113_dispatch_based_sales_summary",
    //     navLink: "/r113_dispatch_based_sales_summary",
    //   },
    //   {
    //     id: "r114_dispatch_summary",
    //     slug: "r114_dispatch_summary",
    //     title: "R114 - Dispatch Summary",
    //     text: "r114_dispatch_summary",
    //     navLink: "/r114_dispatch_summary",
    //   },
    //   {
    //     id: "r115_stock_summary",
    //     slug: "r115_stock_summary",
    //     title: "R115 - Stock Summary",
    //     text: "r115_stock_summary",
    //     navLink: "/r115_stock_summary",
    //   },
    //   {
    //     id: "r116_order_booker_outlet_activity",
    //     slug: "r116_order_booker_outlet_activity",
    //     title: "R116 - Order Booker / Outlet Activity",
    //     text: "r116_order_booker_outlet_activity",
    //     navLink: "/r116_order_booker_outlet_activity",
    //   },
    //   {
    //     id: "r117_backorder_summary",
    //     slug: "r117_backorder_summary",
    //     title: "R117 - Backorder Summary",
    //     text: "r117_backorder_summary",
    //     navLink: "/r117_backorder_summary",
    //   },
    //   {
    //     id: "r118_lifting_summary_converted_cases",
    //     slug: "r118_lifting_summary_converted_cases",
    //     title: "R118 - Lifting Summary / Converted Cases",
    //     text: "r118_lifting_summary_converted_cases",
    //     navLink: "/r118_lifting_summary_converted_cases",
    //   },
    //   {
    //     id: "r119_lifting_package_distributor",
    //     slug: "r119_lifting_package_distributor",
    //     title: "R119 - Lifting / Package and Distributor",
    //     text: "r119_lifting_package_distributor",
    //     navLink: "/r119_lifting_package_distributor",
    //   },
    //   {
    //     id: "r120_order_booker_tracking",
    //     slug: "r120_order_booker_tracking",
    //     title: "R120 - Order Booker Tracking",
    //     text: "r120_order_booker_tracking",
    //     navLink: "/r120_order_booker_tracking",
    //   },
    //   {
    //     id: "r121_lifting_summary_invoice_value",
    //     slug: "r121_lifting_summary_invoice_value",
    //     title: "R121 - Lifting Summary / Invoice Value",
    //     text: "r121_lifting_summary_invoice_value",
    //     navLink: "/r121_lifting_summary_invoice_value",
    //   },
    //   {
    //     id: "r122_lifting_segregation",
    //     slug: "r122_lifting_segregation",
    //     title: "R122 - Lifting Segregation",
    //     text: "r122_lifting_segregation",
    //     navLink: "/r122_lifting_segregation",
    //   },
    //   {
    //     id: "r123_timestamp_analysis",
    //     slug: "r123_timestamp_analysis",
    //     title: "R123 - Timestamp Analysis",
    //     text: "r123_timestamp_analysis",
    //     navLink: "/r123_timestamp_analysis",
    //   },
    //   {
    //     id: "r125_time_distance_analysis",
    //     slug: "r125_time_distance_analysis",
    //     title: "R125 - Time & Distance Analysis",
    //     text: "r125_time_distance_analysis",
    //     navLink: "/r125_time_distance_analysis",
    //   },
    //   {
    //     id: "r126_outlet_profile",
    //     slug: "r126_outlet_profile",
    //     title: "R126 - Outlet Profile",
    //     text: "r126_outlet_profile",
    //     navLink: "/r126_outlet_profile",
    //   },
    //   {
    //     id: "r127_complaint_list",
    //     slug: "r127_complaint_list",
    //     title: "R127 - Complaint List",
    //     text: "r127_complaint_list",
    //     navLink: "/r127_complaint_list",
    //   },
    //   {
    //     id: "r128_pjp_list",
    //     slug: "r128_pjp_list",
    //     title: "R128 - PJP List",
    //     text: "r128_pjp_list",
    //     navLink: "/r128_pjp_list",
    //   },
    //   {
    //     id: "r129_outlet_inactivity_aging",
    //     slug: "r129_outlet_inactivity_aging",
    //     title: "R129 - Outlet Inactivity Aging",
    //     text: "r129_outlet_inactivity_aging",
    //     navLink: "/r129_outlet_inactivity_aging",
    //   },
    //   {
    //     id: "r130_outlet_inactivity_aging_2",
    //     slug: "r130_outlet_inactivity_aging_2",
    //     title: "R130 - Outlet Inactivity Aging",
    //     text: "r130_outlet_inactivity_aging_2",
    //     navLink: "/r130_outlet_inactivity_aging_2",
    //   },
    //   {
    //     id: "r132_sales_versus_targets",
    //     slug: "r132_sales_versus_targets",
    //     title: "R132 - Sales versus Targets",
    //     text: "r132_sales_versus_targets",
    //     navLink: "/r132_sales_versus_targets",
    //   },
    //   {
    //     id: "r133_lifting_versus_targets",
    //     slug: "r133_lifting_versus_targets",
    //     title: "R133 - Lifting versus Targets",
    //     text: "r133_lifting_versus_targets",
    //     navLink: "/r133_lifting_versus_targets",
    //   },
    //   {
    //     id: "r135_complaint_list_tot",
    //     slug: "r135_complaint_list_tot",
    //     title: "R135 - Complaint List / TOT",
    //     text: "r135_complaint_list_tot",
    //     navLink: "/r135_complaint_list_tot",
    //   },
    //   {
    //     id: "r136_complaint_status",
    //     slug: "r136_complaint_status",
    //     title: "R136 - Complaint Status",
    //     text: "r136_complaint_status",
    //     navLink: "/r136_complaint_status",
    //   },
    //   {
    //     id: "r137_complaint_status_2",
    //     slug: "r137_complaint_status_2",
    //     title: "R137 - Complaint Status",
    //     text: "r137_complaint_status_2",
    //     navLink: "/r137_complaint_status_2",
    //   },
    //   {
    //     id: "r138_hand_to_hand_discount",
    //     slug: "r138_hand_to_hand_discount",
    //     title: "R138 - Hand to Hand Discount",
    //     text: "r138_hand_to_hand_discount",
    //     navLink: "/r138_hand_to_hand_discount",
    //   },
    //   {
    //     id: "r139_hand_to_hand_discount_2",
    //     slug: "r139_hand_to_hand_discount_2",
    //     title: "R139 - Hand to Hand Discount",
    //     text: "r139_hand_to_hand_discount_2",
    //     navLink: "/r139_hand_to_hand_discount_2",
    //   },
    //   {
    //     id: "r140_complaint_list_tot_2",
    //     slug: "r140_complaint_list_tot_2",
    //     title: "R140 - Complaint List / TOT",
    //     text: "r140_complaint_list_tot_2",
    //     navLink: "/r140_complaint_list_tot_2",
    //   },
    //   {
    //     id: "r142_invoices_not_lifted",
    //     slug: "r142_invoices_not_lifted",
    //     title: "R142 - Invoices not Lifted",
    //     text: "r142_invoices_not_lifted",
    //     navLink: "/r142_invoices_not_lifted",
    //   },
    //   {
    //     id: "r143_pending_complaints_merchandising",
    //     slug: "r143_pending_complaints_merchandising",
    //     title: "R143 - Pending Complaints Merchandising",
    //     text: "r143_pending_complaints_merchandising",
    //     navLink: "/r143_pending_complaints_merchandising",
    //   },
    //   {
    //     id: "r144_invoice_summary",
    //     slug: "r144_invoice_summary",
    //     title: "R144 - Invoice Summary",
    //     text: "r144_invoice_summary",
    //     navLink: "/r144_invoice_summary",
    //   },
    //   {
    //     id: "r145_cancelled_orders",
    //     slug: "r145_cancelled_orders",
    //     title: "R145 - Cancelled Orders",
    //     text: "r145_cancelled_orders",
    //     navLink: "/r145_cancelled_orders",
    //   },
    //   {
    //     id: "r146_customer_ledger",
    //     slug: "r146_customer_ledger",
    //     title: "R146 - Customer Ledger",
    //     text: "r146_customer_ledger",
    //     navLink: "/r146_customer_ledger",
    //   },
    //   {
    //     id: "r147_cash_instrument_ledger",
    //     slug: "r147_cash_instrument_ledger",
    //     title: "R147 - Cash Instrument Ledger",
    //     text: "r147_cash_instrument_ledger",
    //     navLink: "/r147_cash_instrument_ledger",
    //   },
    //   {
    //     id: "r148_cash_instrument_summary",
    //     slug: "r148_cash_instrument_summary",
    //     title: "R148 - Cash Instrument Summary",
    //     text: "r148_cash_instrument_summary",
    //     navLink: "/r148_cash_instrument_summary",
    //   },
    //   {
    //     id: "r149_payment_posting",
    //     slug: "r149_payment_posting",
    //     title: "R149 - Payment Posting",
    //     text: "r149_payment_posting",
    //     navLink: "/r149_payment_posting",
    //   },
    //   {
    //     id: "r150_kpi_distributor",
    //     slug: "r150_kpi_distributor",
    //     title: "R150 - KPI / Distributor",
    //     text: "r150_kpi_distributor",
    //     navLink: "/r150_kpi_distributor",
    //   },
    //   {
    //     id: "r151_cash_receipt_summary",
    //     slug: "r151_cash_receipt_summary",
    //     title: "R151 - Cash Receipt Summary",
    //     text: "r151_cash_receipt_summary",
    //     navLink: "/r151_cash_receipt_summary",
    //   },
    //   {
    //     id: "r152_customer_credit_summary",
    //     slug: "r152_customer_credit_summary",
    //     title: "R152 - Customer Credit Summary",
    //     text: "r152_customer_credit_summary",
    //     navLink: "/r152_customer_credit_summary",
    //   },
    //   {
    //     id: "r153_cash_instrument_ledger_personal",
    //     slug: "r153_cash_instrument_ledger_personal",
    //     title: "R153 - Cash Instrument Ledger (Personal)",
    //     text: "r153_cash_instrument_ledger_personal",
    //     navLink: "/r153_cash_instrument_ledger_personal",
    //   },
    //   {
    //     id: "r154_cash_receipt_summary_personal",
    //     slug: "r154_cash_receipt_summary_personal",
    //     title: "R154 - Cash Receipt Summary (Personal)",
    //     text: "r154_cash_receipt_summary_personal",
    //     navLink: "/r154_cash_receipt_summary_personal",
    //   },
    //   {
    //     id: "r155_posted_invoices",
    //     slug: "r155_posted_invoices",
    //     title: "R155 - Posted Invoices",
    //     text: "r155_posted_invoices",
    //     navLink: "/r155_posted_invoices",
    //   },
    //   {
    //     id: "r156_customer_status",
    //     slug: "r156_customer_status",
    //     title: "R156 - Customer Status",
    //     text: "r156_customer_status",
    //     navLink: "/r156_customer_status",
    //   },
    //   {
    //     id: "r157_posted_invoices_personal",
    //     slug: "r157_posted_invoices_personal",
    //     title: "R157 - Posted Invoices (Personal)",
    //     text: "r157_posted_invoices_personal",
    //     navLink: "/r157_posted_invoices_personal",
    //   },
    //   {
    //     id: "r158_cash_receipt_summary",
    //     slug: "r158_cash_receipt_summary",
    //     title: "R158 - Cash Receipt Summary",
    //     text: "r158_cash_receipt_summary",
    //     navLink: "/r158_cash_receipt_summary",
    //   },
    //   {
    //     id: "r159_cash_receipt_list_personal",
    //     slug: "r159_cash_receipt_list_personal",
    //     title: "R159 - Cash Receipt List (Personal)",
    //     text: "r159_cash_receipt_list_personal",
    //     navLink: "/r159_cash_receipt_list_personal",
    //   },
    //   {
    //     id: "r160_customer_account_adjustments",
    //     slug: "r160_customer_account_adjustments",
    //     title: "R160 - Customer Account Adjustments",
    //     text: "r160_customer_account_adjustments",
    //     navLink: "/r160_customer_account_adjustments",
    //   },
    //   {
    //     id: "r161_invoices_not_posted",
    //     slug: "r161_invoices_not_posted",
    //     title: "R161 - Invoices not Posted",
    //     text: "r161_invoices_not_posted",
    //     navLink: "/r161_invoices_not_posted",
    //   },
    //   {
    //     id: "r162_pending_payment_posting",
    //     slug: "r162_pending_payment_posting",
    //     title: "R162 - Pending Payment Posting",
    //     text: "r162_pending_payment_posting",
    //     navLink: "/r162_pending_payment_posting",
    //   },
    //   {
    //     id: "r163_sales_outlet_types",
    //     slug: "r163_sales_outlet_types",
    //     title: "R163 - Sales / Outlet Types",
    //     text: "r163_sales_outlet_types",
    //     navLink: "/r163_sales_outlet_types",
    //   },
    //   {
    //     id: "r164_discounted_outlets",
    //     slug: "r164_discounted_outlets",
    //     title: "R164 - Discounted Outlets",
    //     text: "r164_discounted_outlets",
    //     navLink: "/r164_discounted_outlets",
    //   },
    //   {
    //     id: "r165_unproductive_outlets",
    //     slug: "r165_unproductive_outlets",
    //     title: "R165 - Unproductive Outlets",
    //     text: "r165_unproductive_outlets",
    //     navLink: "/r165_unproductive_outlets",
    //   },
    //   {
    //     id: "r166_manual_sales_analysis",
    //     slug: "r166_manual_sales_analysis",
    //     title: "R166 - Manual Sales Analysis",
    //     text: "r166_manual_sales_analysis",
    //     navLink: "/r166_manual_sales_analysis",
    //   },
    //   {
    //     id: "r167_active_promotions",
    //     slug: "r167_active_promotions",
    //     title: "R167 - Active Promotions",
    //     text: "r167_active_promotions",
    //     navLink: "/r167_active_promotions",
    //   },
    //   {
    //     id: "r168_distributor_credit_slips",
    //     slug: "r168_distributor_credit_slips",
    //     title: "R168 - Distributor Credit Slips",
    //     text: "r168_distributor_credit_slips",
    //     navLink: "/r168_distributor_credit_slips",
    //   },
    //   {
    //     id: "r169_order_booker_sales",
    //     slug: "r169_order_booker_sales",
    //     title: "R169 - Order Booker Sales",
    //     text: "r169_order_booker_sales",
    //     navLink: "/r169_order_booker_sales",
    //   },
    //   {
    //     id: "r170_one_time_credit_issuance",
    //     slug: "r170_one_time_credit_issuance",
    //     title: "R170 - One Time Credit Issuance",
    //     text: "r170_one_time_credit_issuance",
    //     navLink: "/r170_one_time_credit_issuance",
    //   },
    //   {
    //     id: "r171_instrument_receipt_summary",
    //     slug: "r171_instrument_receipt_summary",
    //     title: "R171 - Instrument Receipt Summary",
    //     text: "r171_instrument_receipt_summary",
    //     navLink: "/r171_instrument_receipt_summary",
    //   },
    //   {
    //     id: "r172_outlet_planned_vs_actual_sales",
    //     slug: "r172_outlet_planned_vs_actual_sales",
    //     title: "R172 - Outlet Planned vs Actual Sales",
    //     text: "r172_outlet_planned_vs_actual_sales",
    //     navLink: "/r172_outlet_planned_vs_actual_sales",
    //   },
    //   {
    //     id: "r173_order_booker_incentive",
    //     slug: "r173_order_booker_incentive",
    //     title: "R173 - Order Booker Incentive",
    //     text: "r173_order_booker_incentive",
    //     navLink: "/r173_order_booker_incentive",
    //   },
    //   {
    //     id: "r174_active_primary_promotions",
    //     slug: "r174_active_primary_promotions",
    //     title: "R174 - Active Primary Promotions",
    //     text: "r174_active_primary_promotions",
    //     navLink: "/r174_active_primary_promotions",
    //   },
    //   {
    //     id: "r175_pre_selling_market_coverage",
    //     slug: "r175_pre_selling_market_coverage",
    //     title: "R175 - Pre-Selling Market Coverage",
    //     text: "r175_pre_selling_market_coverage",
    //     navLink: "/r175_pre_selling_market_coverage",
    //   },
    //   {
    //     id: "r176_upfront_discount",
    //     slug: "r176_upfront_discount",
    //     title: "R176 - Upfront Discount",
    //     text: "r176_upfront_discount",
    //     navLink: "/r176_upfront_discount",
    //   },
    //   {
    //     id: "r177_distributor_ledger_secondary_user",
    //     slug: "r177_distributor_ledger_secondary_user",
    //     title: "R177 - Distributor Ledger (Secondary User)",
    //     text: "r177_distributor_ledger_secondary_user",
    //     navLink: "/r177_distributor_ledger_secondary_user",
    //   },
    //   {
    //     id: "r178_active_primary_promotions",
    //     slug: "r178_active_primary_promotions",
    //     title: "R178 - Active Primary Promotions",
    //     text: "r178_active_primary_promotions",
    //     navLink: "/r178_active_primary_promotions",
    //   },
    //   {
    //     id: "r179_new_empty_issued",
    //     slug: "r179_new_empty_issued",
    //     title: "R179 - New Empty Issued",
    //     text: "r179_new_empty_issued",
    //     navLink: "/r179_new_empty_issued",
    //   },
    //   {
    //     id: "r180_old_empty_purchase",
    //     slug: "r180_old_empty_purchase",
    //     title: "R180 - Old Empty Purchase",
    //     text: "r180_old_empty_purchase",
    //     navLink: "/r180_old_empty_purchase",
    //   },
    //   {
    //     id: "r181_empty_transactions",
    //     slug: "r181_empty_transactions",
    //     title: "R181 - Empty Transactions",
    //     text: "r181_empty_transactions",
    //     navLink: "/r181_empty_transactions",
    //   },
    //   {
    //     id: "r182_empty_reconciliation",
    //     slug: "r182_empty_reconciliation",
    //     title: "R182 - Empty Reconciliation",
    //     text: "r182_empty_reconciliation",
    //     navLink: "/r182_empty_reconciliation",
    //   },
    //   {
    //     id: "r183_primary_sales_vs_targets",
    //     slug: "r183_primary_sales_vs_targets",
    //     title: "R183 - Primary Sales vs Targets",
    //     text: "r183_primary_sales_vs_targets",
    //     navLink: "/r183_primary_sales_vs_targets",
    //   },
    //   {
    //     id: "r184_average_price",
    //     slug: "r184_average_price",
    //     title: "R184 - Average Price",
    //     text: "r184_average_price",
    //     navLink: "/r184_average_price",
    //   },
    //   {
    //     id: "r185_revenue_per_case",
    //     slug: "r185_revenue_per_case",
    //     title: "R185 - Revenue Per Case",
    //     text: "r185_revenue_per_case",
    //     navLink: "/r185_revenue_per_case",
    //   },
    //   {
    //     id: "r186_revenue_per_case",
    //     slug: "r186_revenue_per_case",
    //     title: "R186 - Revenue Per Case",
    //     text: "r186_revenue_per_case",
    //     navLink: "/r186_revenue_per_case",
    //   },
    //   {
    //     id: "r187_empty_ledger",
    //     slug: "r187_empty_ledger",
    //     title: "R187 - Empty Ledger",
    //     text: "r187_empty_ledger",
    //     navLink: "/r187_empty_ledger",
    //   },
    //   {
    //     id: "r188_orders_package_and_outlet",
    //     slug: "r188_orders_package_and_outlet",
    //     title: "R188 - Orders / Package and Outlet",
    //     text: "r188_orders_package_and_outlet",
    //     navLink: "/r188_orders_package_and_outlet",
    //   },
    //   {
    //     id: "r189_per_case_discounts",
    //     slug: "r189_per_case_discounts",
    //     title: "R189 - Per Case Discounts",
    //     text: "r189_per_case_discounts",
    //     navLink: "/r189_per_case_discounts",
    //   },
    //   {
    //     id: "r190_distributor_empty_status",
    //     slug: "r190_distributor_empty_status",
    //     title: "R190 - Distributor Empty Status",
    //     text: "r190_distributor_empty_status",
    //     navLink: "/r190_distributor_empty_status",
    //   },
    //   {
    //     id: "r191_empty_receipt_list",
    //     slug: "r191_empty_receipt_list",
    //     title: "R191 - Empty Receipt List",
    //     text: "r191_empty_receipt_list",
    //     navLink: "/r191_empty_receipt_list",
    //   },
    //   {
    //     id: "r192_empty_activity",
    //     slug: "r192_empty_activity",
    //     title: "R192 - Empty Activity",
    //     text: "r192_empty_activity",
    //     navLink: "/r192_empty_activity",
    //   },
    //   {
    //     id: "r193_outlet_sales",
    //     slug: "r193_outlet_sales",
    //     title: "R193 - Outlet Sales",
    //     text: "r193_outlet_sales",
    //     navLink: "/r193_outlet_sales",
    //   },
    //   {
    //     id: "r194_empty_receipts",
    //     slug: "r194_empty_receipts",
    //     title: "R194 - Empty Receipts",
    //     text: "r194_empty_receipts",
    //     navLink: "/r194_empty_receipts",
    //   },
    //   {
    //     id: "r195_empty_receipt_summary",
    //     slug: "r195_empty_receipt_summary",
    //     title: "R195 - Empty Receipt Summary",
    //     text: "r195_empty_receipt_summary",
    //     navLink: "/r195_empty_receipt_summary",
    //   },
    //   {
    //     id: "r196_outlet_productivity",
    //     slug: "r196_outlet_productivity",
    //     title: "R196 - Outlet Productivity",
    //     text: "r196_outlet_productivity",
    //     navLink: "/r196_outlet_productivity",
    //   },
    //   {
    //     id: "r197_customer_discounts",
    //     slug: "r197_customer_discounts",
    //     title: "R197 - Customer Discounts",
    //     text: "r197_customer_discounts",
    //     navLink: "/r197_customer_discounts",
    //   },
    //   {
    //     id: "r198_order_booker_sales",
    //     slug: "r198_order_booker_sales",
    //     title: "R198 - Order Booker Sales",
    //     text: "r198_order_booker_sales",
    //     navLink: "/r198_order_booker_sales",
    //   },
    //   {
    //     id: "r199_lifting_without_targets",
    //     slug: "r199_lifting_without_targets",
    //     title: "R199 - Lifting without Targets",
    //     text: "r199_lifting_without_targets",
    //     navLink: "/r199_lifting_without_targets",
    //   },
    //   {
    //     id: "r200_distributor_sales_summary",
    //     slug: "r200_distributor_sales_summary",
    //     title: "R200 - Distributor Sales Summary",
    //     text: "r200_distributor_sales_summary",
    //     navLink: "/r200_distributor_sales_summary",
    //   },
    //   {
    //     id: "r201_lifting_attainment",
    //     slug: "r201_lifting_attainment",
    //     title: "R201 - Lifting Attainment",
    //     text: "r201_lifting_attainment",
    //     navLink: "/r201_lifting_attainment",
    //   },
    //   {
    //     id: "r202_distributor_score_card",
    //     slug: "r202_distributor_score_card",
    //     title: "R202 - Distributor Score Card",
    //     text: "r202_distributor_score_card",
    //     navLink: "/r202_distributor_score_card",
    //   },
    //   {
    //     id: "r203_revenue_based_lifting",
    //     slug: "r203_revenue_based_lifting",
    //     title: "R203 - Revenue based Lifting",
    //     text: "r203_revenue_based_lifting",
    //     navLink: "/r203_revenue_based_lifting",
    //   },
    //   {
    //     id: "r204_distributor_area_allocation",
    //     slug: "r204_distributor_area_allocation",
    //     title: "R204 - Distributor Area Allocation",
    //     text: "r204_distributor_area_allocation",
    //     navLink: "/r204_distributor_area_allocation",
    //   },
    //   {
    //     id: "r205_sales_segregation",
    //     slug: "r205_sales_segregation",
    //     title: "R205 - Sales Segregation",
    //     text: "r205_sales_segregation",
    //     navLink: "/r205_sales_segregation",
    //   },
    //   {
    //     id: "r206_active_empty_credit_limits",
    //     slug: "r206_active_empty_credit_limits",
    //     title: "R206 - Active Empty Credit Limits",
    //     text: "r206_active_empty_credit_limits",
    //     navLink: "/r206_active_empty_credit_limits",
    //   },
    //   {
    //     id: "r207_empty_credit_status",
    //     slug: "r207_empty_credit_status",
    //     title: "R207 - Empty Credit Status",
    //     text: "r207_empty_credit_status",
    //     navLink: "/r207_empty_credit_status",
    //   },
    //   {
    //     id: "r208_lifting_vs_secondary",
    //     slug: "r208_lifting_vs_secondary",
    //     title: "R208 - Lifting vs. Secondary",
    //     text: "r208_lifting_vs_secondary",
    //     navLink: "/r208_lifting_vs_secondary",
    //   },
    //   {
    //     id: "r209_order_booker_tracking_secondary_user",
    //     slug: "r209_order_booker_tracking_secondary_user",
    //     title: "R209 - Order Booker Tracking (Secondary User)",
    //     text: "r209_order_booker_tracking_secondary_user",
    //     navLink: "/r209_order_booker_tracking_secondary_user",
    //   },
    //   {
    //     id: "r210_pjp_list_secondary_user",
    //     slug: "r210_pjp_list_secondary_user",
    //     title: "R210 - PJP List (Secondary User)",
    //     text: "r210_pjp_list_secondary_user",
    //     navLink: "/r210_pjp_list_secondary_user",
    //   },
    //   {
    //     id: "r211_kpi_orderbooker_secondary_user",
    //     slug: "r211_kpi_orderbooker_secondary_user",
    //     title: "R211 - KPI / Orderbooker (Secondary User)",
    //     text: "r211_kpi_orderbooker_secondary_user",
    //     navLink: "/r211_kpi_orderbooker_secondary_user",
    //   },
    //   {
    //     id: "r212_lifting_orders_secondary_user",
    //     slug: "r212_lifting_orders_secondary_user",
    //     title: "R212 - Lifting Orders (Secondary User)",
    //     text: "r212_lifting_orders_secondary_user",
    //     navLink: "/r212_lifting_orders_secondary_user",
    //   },
    //   {
    //     id: "r213_empty_status_secondary_user",
    //     slug: "r213_empty_status_secondary_user",
    //     title: "R213 - Empty Status (Secondary User)",
    //     text: "r213_empty_status_secondary_user",
    //     navLink: "/r213_empty_status_secondary_user",
    //   },
    //   {
    //     id: "r214_order_booker_sales_secondary_user",
    //     slug: "r214_order_booker_sales_secondary_user",
    //     title: "R214 - Order Booker Sales (Secondary User)",
    //     text: "r214_order_booker_sales_secondary_user",
    //     navLink: "/r214_order_booker_sales_secondary_user",
    //   },
    //   {
    //     id: "r215_order_booker_score_card",
    //     slug: "r215_order_booker_score_card",
    //     title: "R215 - Order Booker Score Card",
    //     text: "r215_order_booker_score_card",
    //     navLink: "/r215_order_booker_score_card",
    //   },
    //   {
    //     id: "r216_credit_limit_processing",
    //     slug: "r216_credit_limit_processing",
    //     title: "R216 - Credit Limit Processing",
    //     text: "r216_credit_limit_processing",
    //     navLink: "/r216_credit_limit_processing",
    //   },
    //   {
    //     id: "r217_stock_summary_secondary_user",
    //     slug: "r217_stock_summary_secondary_user",
    //     title: "R217 - Stock Summary (Secondary User)",
    //     text: "r217_stock_summary_secondary_user",
    //     navLink: "/r217_stock_summary_secondary_user",
    //   },
    //   {
    //     id: "r218_outsourcing_sales_summary",
    //     slug: "r218_outsourcing_sales_summary",
    //     title: "R218 - Outsourcing Sales Summary",
    //     text: "r218_outsourcing_sales_summary",
    //     navLink: "/r218_outsourcing_sales_summary",
    //   },
    //   {
    //     id: "r219_outsourcing_purchases",
    //     slug: "r219_outsourcing_purchases",
    //     title: "R219 - Outsourcing Purchases",
    //     text: "r219_outsourcing_purchases",
    //     navLink: "/r219_outsourcing_purchases",
    //   },
    //   {
    //     id: "r220_approved_credit_limits",
    //     slug: "r220_approved_credit_limits",
    //     title: "R220 - Approved Credit Limits",
    //     text: "r220_approved_credit_limits",
    //     navLink: "/r220_approved_credit_limits",
    //   },
    //   {
    //     id: "r221_empty_issuance",
    //     slug: "r221_empty_issuance",
    //     title: "R221 - Empty Issuance",
    //     text: "r221_empty_issuance",
    //     navLink: "/r221_empty_issuance",
    //   },
    //   {
    //     id: "r222_outsourcing_sales_list",
    //     slug: "r222_outsourcing_sales_list",
    //     title: "R222 - Outsourcing Sales List",
    //     text: "r222_outsourcing_sales_list",
    //     navLink: "/r222_outsourcing_sales_list",
    //   },
    //   {
    //     id: "r223_distributor_per_case_discount",
    //     slug: "r223_distributor_per_case_discount",
    //     title: "R223 - Distributor Per Case Discount",
    //     text: "r223_distributor_per_case_discount",
    //     navLink: "/r223_distributor_per_case_discount",
    //   },
    //   {
    //     id: "r224_order_booker_timestamps",
    //     slug: "r224_order_booker_timestamps",
    //     title: "R224 - Order Booker Timestamps",
    //     text: "r224_order_booker_timestamps",
    //     navLink: "/r224_order_booker_timestamps",
    //   },
    //   {
    //     id: "r225_empty_receipts",
    //     slug: "r225_empty_receipts",
    //     title: "R225 - Empty Receipts",
    //     text: "r225_empty_receipts",
    //     navLink: "/r225_empty_receipts",
    //   },
    //   {
    //     id: "r226_secondary_sales_verification",
    //     slug: "r226_secondary_sales_verification",
    //     title: "R226 - Secondary Sales Verification",
    //     text: "r226_secondary_sales_verification",
    //     navLink: "/r226_secondary_sales_verification",
    //   },
    //   {
    //     id: "r227_printed_sampling_slips",
    //     slug: "r227_printed_sampling_slips",
    //     title: "R227 - Printed Sampling Slips",
    //     text: "r227_printed_sampling_slips",
    //     navLink: "/r227_printed_sampling_slips",
    //   },
    //   {
    //     id: "r228_sales_package_and_outlet",
    //     slug: "r228_sales_package_and_outlet",
    //     title: "R228 - Sales / Package and Outlet",
    //     text: "r228_sales_package_and_outlet",
    //     navLink: "/r228_sales_package_and_outlet",
    //   },
    //   {
    //     id: "r229_pjp_kpis",
    //     slug: "r229_pjp_kpis",
    //     title: "R229 - PJP KPIs",
    //     text: "r229_pjp_kpis",
    //     navLink: "/r229_pjp_kpis",
    //   },
    //   {
    //     id: "r230_distributor_kpis",
    //     slug: "r230_distributor_kpis",
    //     title: "R230 - Distributor KPIs",
    //     text: "r230_distributor_kpis",
    //     navLink: "/r230_distributor_kpis",
    //   },
    //   {
    //     id: "r231_distributor_stock_analysis",
    //     slug: "r231_distributor_stock_analysis",
    //     title: "R231 - Distributor Stock Analysis",
    //     text: "r231_distributor_stock_analysis",
    //     navLink: "/r231_distributor_stock_analysis",
    //   },
    //   {
    //     id: "r232_primary_and_secondary_sales",
    //     slug: "r232_primary_and_secondary_sales",
    //     title: "R232 - Primary and Secondary Sales",
    //     text: "r232_primary_and_secondary_sales",
    //     navLink: "/r232_primary_and_secondary_sales",
    //   },
    //   {
    //     id: "r233_primary_and_secondary_sales",
    //     slug: "r233_primary_and_secondary_sales",
    //     title: "R233 - Primary and Secondary Sales",
    //     text: "r233_primary_and_secondary_sales",
    //     navLink: "/r233_primary_and_secondary_sales",
    //   },
    //   {
    //     id: "r234_customer_credit_summary",
    //     slug: "r234_customer_credit_summary",
    //     title: "R234 - Customer Credit Summary",
    //     text: "r234_customer_credit_summary",
    //     navLink: "/r234_customer_credit_summary",
    //   },
    //   {
    //     id: "r235_volume_analysis",
    //     slug: "r235_volume_analysis",
    //     title: "R235 - Volume Analysis",
    //     text: "r235_volume_analysis",
    //     navLink: "/r235_volume_analysis",
    //   },
    //   {
    //     id: "r236_sku_and_sales_analysis",
    //     slug: "r236_sku_and_sales_analysis",
    //     title: "R236 - SKU and Sales Analysis",
    //     text: "r236_sku_and_sales_analysis",
    //     navLink: "/r236_sku_and_sales_analysis",
    //   },
    //   {
    //     id: "r237_distributor_statement",
    //     slug: "r237_distributor_statement",
    //     title: "R237 - Distributor Statement",
    //     text: "r237_distributor_statement",
    //     navLink: "/r237_distributor_statement",
    //   },
    //   {
    //     id: "r2381_mobile_census",
    //     slug: "r2381_mobile_census",
    //     title: "R2381 - Mobile Census",
    //     text: "r2381_mobile_census",
    //     navLink: "/r2381_mobile_census",
    //   },
    //   {
    //     id: "r2391_mobile_census_summary",
    //     slug: "r2391_mobile_census_summary",
    //     title: "R2391 - Mobile Census Summary",
    //     text: "r2391_mobile_census_summary",
    //     navLink: "/r2391_mobile_census_summary",
    //   },
    //   {
    //     id: "r2381_mobile_census",
    //     slug: "r2381_mobile_census",
    //     title: "R2381 - Mobile Census",
    //     text: "r2381_mobile_census",
    //     navLink: "/r2381_mobile_census",
    //   },
    //   {
    //     id: "r2391_mobile_census_summary",
    //     slug: "r2391_mobile_census_summary",
    //     title: "R2391 - Mobile Census Summary",
    //     text: "r2391_mobile_census_summary",
    //     navLink: "/r2391_mobile_census_summary",
    //   },
    //   {
    //     id: "r240_per_case_discount_approval",
    //     slug: "r240_per_case_discount_approval",
    //     title: "R240 - Per Case Discount Approval",
    //     text: "r240_per_case_discount_approval",
    //     navLink: "/r240_per_case_discount_approval",
    //   },
    //   {
    //     id: "r241_per_case_discount_approval",
    //     slug: "r241_per_case_discount_approval",
    //     title: "R241 - Per Case Discount Approval",
    //     text: "r241_per_case_discount_approval",
    //     navLink: "/r241_per_case_discount_approval",
    //   },
    //   {
    //     id: "r242_mobile_census_summary_edit",
    //     slug: "r242_mobile_census_summary_edit",
    //     title: "R242 - Mobile Census Summary [Edit]",
    //     text: "r242_mobile_census_summary_edit",
    //     navLink: "/r242_mobile_census_summary_edit",
    //   },
    //   {
    //     id: "r243_chiller_exception",
    //     slug: "r243_chiller_exception",
    //     title: "R243 - Chiller Exception",
    //     text: "r243_chiller_exception",
    //     navLink: "/r243_chiller_exception",
    //   },
    //   {
    //     id: "r244_help_desk_sales_service_requests",
    //     slug: "r244_help_desk_sales_service_requests",
    //     title: "R244 - Help Desk Sales Service Requests",
    //     text: "r244_help_desk_sales_service_requests",
    //     navLink: "/r244_help_desk_sales_service_requests",
    //   },
    //   {
    //     id: "r245_help_desk_quality_requests",
    //     slug: "r245_help_desk_quality_requests",
    //     title: "R245 - Help Desk Quality Requests",
    //     text: "r245_help_desk_quality_requests",
    //     navLink: "/r245_help_desk_quality_requests",
    //   },
    //   {
    //     id: "r246_help_desk_mem_requests",
    //     slug: "r246_help_desk_mem_requests",
    //     title: "R246 - Help Desk MEM Requests",
    //     text: "r246_help_desk_mem_requests",
    //     navLink: "/r246_help_desk_mem_requests",
    //   },
    //   {
    //     id: "r247_new_outlet_request_summary",
    //     slug: "r247_new_outlet_request_summary",
    //     title: "R247 - New Outlet Request Summary",
    //     text: "r247_new_outlet_request_summary",
    //     navLink: "/r247_new_outlet_request_summary",
    //   },
    //   {
    //     id: "r248_help_desk_other_requests",
    //     slug: "r248_help_desk_other_requests",
    //     title: "R248 - Help Desk Other Requests",
    //     text: "r248_help_desk_other_requests",
    //     navLink: "/r248_help_desk_other_requests",
    //   },
    //   {
    //     id: "r249_cooler_scanning_visits",
    //     slug: "r249_cooler_scanning_visits",
    //     title: "R249 - Cooler Scanning Visits",
    //     text: "r249_cooler_scanning_visits",
    //     navLink: "/r249_cooler_scanning_visits",
    //   },
    //   {
    //     id: "r250_outlet_ledger",
    //     slug: "r250_outlet_ledger",
    //     title: "R250 - Outlet Ledger",
    //     text: "r250_outlet_ledger",
    //     navLink: "/r250_outlet_ledger",
    //   },
    //   {
    //     id: "r251_outlet_discounts_requests",
    //     slug: "r251_outlet_discounts_requests",
    //     title: "R251 - Outlet Discounts Requests",
    //     text: "r251_outlet_discounts_requests",
    //     navLink: "/r251_outlet_discounts_requests",
    //   },
    //   {
    //     id: "r252_outlet_sales",
    //     slug: "r252_outlet_sales",
    //     title: "R252 - Outlet Sales",
    //     text: "r252_outlet_sales",
    //     navLink: "/r252_outlet_sales",
    //   },
    //   {
    //     id: "r253_outlet_discount",
    //     slug: "r253_outlet_discount",
    //     title: "R253 - Outlet Discount",
    //     text: "r253_outlet_discount",
    //     navLink: "/r253_outlet_discount",
    //   },
    //   {
    //     id: "r254_stock_dispatching_report",
    //     slug: "r254_stock_dispatching_report",
    //     title: "R254 - Stock Dispatching Report",
    //     text: "r254_stock_dispatching_report",
    //     navLink: "/r254_stock_dispatching_report",
    //   },
    //   {
    //     id: "r255_stock_dispatching_report",
    //     slug: "r255_stock_dispatching_report",
    //     title: "R255 - Stock Dispatching Report",
    //     text: "r255_stock_dispatching_report",
    //     navLink: "/r255_stock_dispatching_report",
    //   },
    //   {
    //     id: "r256_edisbursement_discounts",
    //     slug: "r256_edisbursement_discounts",
    //     title: "R256 - eDisbursement Discounts",
    //     text: "r256_edisbursement_discounts",
    //     navLink: "/r256_edisbursement_discounts",
    //   },
    //   {
    //     id: "r257_channel_tagging",
    //     slug: "r257_channel_tagging",
    //     title: "R257 - Channel Tagging",
    //     text: "r257_channel_tagging",
    //     navLink: "/r257_channel_tagging",
    //   },
    //   {
    //     id: "r258_channel_tagging_summary",
    //     slug: "r258_channel_tagging_summary",
    //     title: "R258 - Channel Tagging Summary",
    //     text: "r258_channel_tagging_summary",
    //     navLink: "/r258_channel_tagging_summary",
    //   },
    //   {
    //     id: "r259_cooler_scanning_report",
    //     slug: "r259_cooler_scanning_report",
    //     title: "R259 - Cooler Scanning Report",
    //     text: "r259_cooler_scanning_report",
    //     navLink: "/r259_cooler_scanning_report",
    //   },
    //   {
    //     id: "r260_pjp_list_hierarchy",
    //     slug: "r260_pjp_list_hierarchy",
    //     title: "R260 - PJP List (Hierarchy)",
    //     text: "r260_pjp_list_hierarchy",
    //     navLink: "/r260_pjp_list_hierarchy",
    //   },
    //   {
    //     id: "r261_new_outlet_summary_details",
    //     slug: "r261_new_outlet_summary_details",
    //     title: "R261 - New Outlet Summary Details",
    //     text: "r261_new_outlet_summary_details",
    //     navLink: "/r261_new_outlet_summary_details",
    //   },
    //   {
    //     id: "r262_census_summary_map",
    //     slug: "r262_census_summary_map",
    //     title: "R262 - Census Summary Map",
    //     text: "r262_census_summary_map",
    //     navLink: "/r262_census_summary_map",
    //   },
    //   {
    //     id: "r263_retailer_discounts",
    //     slug: "r263_retailer_discounts",
    //     title: "R263 - Retailer Discounts",
    //     text: "r263_retailer_discounts",
    //     navLink: "/r263_retailer_discounts",
    //   },
    //   {
    //     id: "r264_psr_targets",
    //     slug: "r264_psr_targets",
    //     title: "R264 - PSR Targets",
    //     text: "r264_psr_targets",
    //     navLink: "/r264_psr_targets",
    //   },
    //   {
    //     id: "r265_sales_return_report",
    //     slug: "r265_sales_return_report",
    //     title: "R265 - Sales Return Report",
    //     text: "r265_sales_return_report",
    //     navLink: "/r265_sales_return_report",
    //   },
    //   {
    //     id: "r266_distributor_pending_orders",
    //     slug: "r266_distributor_pending_orders",
    //     title: "R266 - Distributor Pending Orders",
    //     text: "r266_distributor_pending_orders",
    //     navLink: "/r266_distributor_pending_orders",
    //   },
    //   {
    //     id: "r267_order_analysis_discounted_outlets",
    //     slug: "r267_order_analysis_discounted_outlets",
    //     title: "R267 - Order Analysis Discounted Outlets",
    //     text: "r267_order_analysis_discounted_outlets",
    //     navLink: "/r267_order_analysis_discounted_outlets",
    //   },
    //   {
    //     id: "r268_test",
    //     slug: "r268_test",
    //     title: "R268 - Test",
    //     text: "r268_test",
    //     navLink: "/r268_test",
    //   },
    //   {
    //     id: "r269_test_outlet_wise",
    //     slug: "r269_test_outlet_wise",
    //     title: "R269 - Test Outlet Wise",
    //     text: "r269_test_outlet_wise",
    //     navLink: "/r269_test_outlet_wise",
    //   },
    //   {
    //     id: "r270_sampling_detail_2",
    //     slug: "r270_sampling_detail_2",
    //     title: "R270 - Sampling Detail-2",
    //     text: "r270_sampling_detail_2",
    //     navLink: "/r270_sampling_detail_2",
    //   },
    //   {
    //     id: "r271_cooler_scanning_report_2",
    //     slug: "r271_cooler_scanning_report_2",
    //     title: "R271 - Cooler Scanning Report 2",
    //     text: "r271_cooler_scanning_report_2",
    //     navLink: "/r271_cooler_scanning_report_2",
    //   },
    //   {
    //     id: "r272_distributor_orders_summary",
    //     slug: "r272_distributor_orders_summary",
    //     title: "R272 - Distributor Orders Summary",
    //     text: "r272_distributor_orders_summary",
    //     navLink: "/r272_distributor_orders_summary",
    //   },
    //   {
    //     id: "r273_empty_credit_limit_processing",
    //     slug: "r273_empty_credit_limit_processing",
    //     title: "R273 - Empty Credit Limit Processing",
    //     text: "r273_empty_credit_limit_processing",
    //     navLink: "/r273_empty_credit_limit_processing",
    //   },
    //   {
    //     id: "r274_order_status_report_primary",
    //     slug: "r274_order_status_report_primary",
    //     title: "R274 - Order Status Report [Primary]",
    //     text: "r274_order_status_report_primary",
    //     navLink: "/r274_order_status_report_primary",
    //   },
    //   {
    //     id: "r275_workflow_request_status",
    //     slug: "r275_workflow_request_status",
    //     title: "R275 - Workflow Request Status",
    //     text: "r275_workflow_request_status",
    //     navLink: "/r275_workflow_request_status",
    //   },
    //   {
    //     id: "r276_order_merchandising_report",
    //     slug: "r276_order_merchandising_report",
    //     title: "R276 - Order Merchandising Report",
    //     text: "r276_order_merchandising_report",
    //     navLink: "/r276_order_merchandising_report",
    //   },
    //   {
    //     id: "r277_distributor_glass_tracking",
    //     slug: "r277_distributor_glass_tracking",
    //     title: "R277 - Distributor Glass Tracking",
    //     text: "r277_distributor_glass_tracking",
    //     navLink: "/r277_distributor_glass_tracking",
    //   },
    //   {
    //     id: "r278_distributor_glass_tracking",
    //     slug: "r278_distributor_glass_tracking",
    //     title: "R278 - Distributor Glass Tracking",
    //     text: "r278_distributor_glass_tracking",
    //     navLink: "/r278_distributor_glass_tracking",
    //   },
    //   {
    //     id: "r279_percase_discount_details",
    //     slug: "r279_percase_discount_details",
    //     title: "R279 - Percase Discount Details",
    //     text: "r279_percase_discount_details",
    //     navLink: "/r279_percase_discount_details",
    //   },
    //   {
    //     id: "r280_hand_to_hand_discount",
    //     slug: "r280_hand_to_hand_discount",
    //     title: "R280 - Hand to Hand Discount",
    //     text: "r280_hand_to_hand_discount",
    //     navLink: "/r280_hand_to_hand_discount",
    //   },
    //   {
    //     id: "r281_dispatch_direct_tracking",
    //     slug: "r281_dispatch_direct_tracking",
    //     title: "R281 - Dispatch Direct Tracking",
    //     text: "r281_dispatch_direct_tracking",
    //     navLink: "/r281_dispatch_direct_tracking",
    //   },
    //   {
    //     id: "r282_dispatch_pjp_tracking",
    //     slug: "r282_dispatch_pjp_tracking",
    //     title: "R282 - Dispatch PJP Tracking",
    //     text: "r282_dispatch_pjp_tracking",
    //     navLink: "/r282_dispatch_pjp_tracking",
    //   },
    //   {
    //     id: "r283_work_with_summary",
    //     slug: "r283_work_with_summary",
    //     title: "R283 - Work With Summary",
    //     text: "r283_work_with_summary",
    //     navLink: "/r283_work_with_summary",
    //   },
    //   {
    //     id: "r284_work_with_score",
    //     slug: "r284_work_with_score",
    //     title: "R284 - Work With Score",
    //     text: "r284_work_with_score",
    //     navLink: "/r284_work_with_score",
    //   },
    //   {
    //     id: "r285_sales_return_posting",
    //     slug: "r285_sales_return_posting",
    //     title: "R285 - Sales Return Posting",
    //     text: "r285_sales_return_posting",
    //     navLink: "/r285_sales_return_posting",
    //   },
    //   {
    //     id: "r286_order_status_report_detail",
    //     slug: "r286_order_status_report_detail",
    //     title: "R286 - Order Status Report [Detail]",
    //     text: "r286_order_status_report_detail",
    //     navLink: "/r286_order_status_report_detail",
    //   },
    //   {
    //     id: "r287_census_map",
    //     slug: "r287_census_map",
    //     title: "R287 - Census Map",
    //     text: "r287_census_map",
    //     navLink: "/r287_census_map",
    //   },
    //   {
    //     id: "r2881_censuscoke_map",
    //     slug: "r2881_censuscoke_map",
    //     title: "R2881 - CensusCoke Map",
    //     text: "r2881_censuscoke_map",
    //     navLink: "/r2881_censuscoke_map",
    //   },
    //   {
    //     id: "r2891_mix_map",
    //     slug: "r2891_mix_map",
    //     title: "R2891 - MIX Map",
    //     text: "r2891_mix_map",
    //     navLink: "/r2891_mix_map",
    //   },
    //   {
    //     id: "r288_retailer_discount_summary",
    //     slug: "r288_retailer_discount_summary",
    //     title: "R288 - Retailer Discount Summary",
    //     text: "r288_retailer_discount_summary",
    //     navLink: "/r288_retailer_discount_summary",
    //   },
    //   {
    //     id: "r290_tot_request_summary",
    //     slug: "r290_tot_request_summary",
    //     title: "R290 - TOT Request Summary",
    //     text: "r290_tot_request_summary",
    //     navLink: "/r290_tot_request_summary",
    //   },
    //   {
    //     id: "r291_signage_request_summary",
    //     slug: "r291_signage_request_summary",
    //     title: "R291 - Signage Request Summary",
    //     text: "r291_signage_request_summary",
    //     navLink: "/r291_signage_request_summary",
    //   },
    //   {
    //     id: "r292_employee_hierarchy",
    //     slug: "r292_employee_hierarchy",
    //     title: "R292 - Employee Hierarchy",
    //     text: "r292_employee_hierarchy",
    //     navLink: "/r292_employee_hierarchy",
    //   },
    //   {
    //     id: "r293_pack_wise_order_summary",
    //     slug: "r293_pack_wise_order_summary",
    //     title: "R293 - Pack Wise Order Summary",
    //     text: "r293_pack_wise_order_summary",
    //     navLink: "/r293_pack_wise_order_summary",
    //   },
    //   {
    //     id: "r294_hand_to_hand_discount",
    //     slug: "r294_hand_to_hand_discount",
    //     title: "R294 - Hand to Hand Discount",
    //     text: "r294_hand_to_hand_discount",
    //     navLink: "/r294_hand_to_hand_discount",
    //   },
    //   {
    //     id: "r295_outlet_advance_amortization",
    //     slug: "r295_outlet_advance_amortization",
    //     title: "R295 - Outlet Advance Amortization",
    //     text: "r295_outlet_advance_amortization",
    //     navLink: "/r295_outlet_advance_amortization",
    //   },
    //   {
    //     id: "r296_psr_attendance",
    //     slug: "r296_psr_attendance",
    //     title: "R296 - PSR Attendance",
    //     text: "r296_psr_attendance",
    //     navLink: "/r296_psr_attendance",
    //   },
    //   {
    //     id: "r297_distributor_percase_discounts_detail",
    //     slug: "r297_distributor_percase_discounts_detail",
    //     title: "R297 - Distributor PerCaseDiscounts [Detail]",
    //     text: "r297_distributor_percase_discounts_detail",
    //     navLink: "/r297_distributor_percase_discounts_detail",
    //   },
    //   {
    //     id: "r298_psr_attendance_detail",
    //     slug: "r298_psr_attendance_detail",
    //     title: "R298 - PSR Attendance[Detail]",
    //     text: "r298_psr_attendance_detail",
    //     navLink: "/r298_psr_attendance_detail",
    //   },
    //   {
    //     id: "r299_distributors_orders",
    //     slug: "r299_distributors_orders",
    //     title: "R299 - Distributors Orders",
    //     text: "r299_distributors_orders",
    //     navLink: "/r299_distributors_orders",
    //   },
    //   {
    //     id: "r300_psr_targets",
    //     slug: "r300_psr_targets",
    //     title: "R300 - PSR Targets",
    //     text: "r300_psr_targets",
    //     navLink: "/r300_psr_targets",
    //   },
    //   {
    //     id: "r301_lifting_distributor_and_order_secondary_user",
    //     slug: "r301_lifting_distributor_and_order_secondary_user",
    //     title: "R301 - Lifting / Distributor and Order [Secondary User]",
    //     text: "r301_lifting_distributor_and_order_secondary_user",
    //     navLink: "/r301_lifting_distributor_and_order_secondary_user",
    //   },
    //   {
    //     id: "r302_feature_list",
    //     slug: "r302_feature_list",
    //     title: "R302 - Feature List",
    //     text: "r302_feature_list",
    //     navLink: "/r302_feature_list",
    //   },
    //   {
    //     id: "r303_registered_cooler_barcodes",
    //     slug: "r303_registered_cooler_barcodes",
    //     title: "R303 - Registered Cooler Barcodes",
    //     text: "r303_registered_cooler_barcodes",
    //     navLink: "/r303_registered_cooler_barcodes",
    //   },
    //   {
    //     id: "r304_feature_list_by_user",
    //     slug: "r304_feature_list_by_user",
    //     title: "R304 - Feature List by User",
    //     text: "r304_feature_list_by_user",
    //     navLink: "/r304_feature_list_by_user",
    //   },
    //   {
    //     id: "r305_base_price_list",
    //     slug: "r305_base_price_list",
    //     title: "R305 - Base Price List",
    //     text: "r305_base_price_list",
    //     navLink: "/r305_base_price_list",
    //   },
    //   {
    //     id: "r306_psr_targets_vs_attainment_detail",
    //     slug: "r306_psr_targets_vs_attainment_detail",
    //     title: "R306 - PSR Targets VS Attainment[Detail]",
    //     text: "r306_psr_targets_vs_attainment_detail",
    //     navLink: "/r306_psr_targets_vs_attainment_detail",
    //   },
    //   {
    //     id: "r307_psr_targets_vs_attainment",
    //     slug: "r307_psr_targets_vs_attainment",
    //     title: "R307 - PSR Targets VS Attainment",
    //     text: "r307_psr_targets_vs_attainment",
    //     navLink: "/r307_psr_targets_vs_attainment",
    //   },
    //   {
    //     id: "r308_market_visit_summary",
    //     slug: "r308_market_visit_summary",
    //     title: "R308 - Market Visit Summary",
    //     text: "r308_market_visit_summary",
    //     navLink: "/r308_market_visit_summary",
    //   },
    //   {
    //     id: "r309_order_booker_outlet_activity_detail",
    //     slug: "r309_order_booker_outlet_activity_detail",
    //     title: "R309 - Order Booker / Outlet Activity [Detail]",
    //     text: "r309_order_booker_outlet_activity_detail",
    //     navLink: "/r309_order_booker_outlet_activity_detail",
    //   },
    //   {
    //     id: "r310_market_visit_tracking",
    //     slug: "r310_market_visit_tracking",
    //     title: "R310 - Market Visit Tracking",
    //     text: "r310_market_visit_tracking",
    //     navLink: "/r310_market_visit_tracking",
    //   },
    //   {
    //     id: "r311_order_booker_outlet_activity_secondary_user",
    //     slug: "r311_order_booker_outlet_activity_secondary_user",
    //     title: "R311 - Order Booker / Outlet Activity (Secondary User)",
    //     text: "r311_order_booker_outlet_activity_secondary_user",
    //     navLink: "/r311_order_booker_outlet_activity_secondary_user",
    //   },
    //   {
    //     id: "r312_empty_credit_limits",
    //     slug: "r312_empty_credit_limits",
    //     title: "R312 - Empty Credit Limits",
    //     text: "r312_empty_credit_limits",
    //     navLink: "/r312_empty_credit_limits",
    //   },
    //   {
    //     id: "r238_order_summary",
    //     slug: "r238_order_summary",
    //     title: "R238 - Order Summary",
    //     text: "r238_order_summary",
    //     navLink: "/r238_order_summary",
    //   },
    //   {
    //     id: "r239_order_summary_secondary_user",
    //     slug: "r239_order_summary_secondary_user",
    //     title: "R239 - Order Summary [Secondary User]",
    //     text: "r239_order_summary_secondary_user",
    //     navLink: "/r239_order_summary_secondary_user",
    //   },
    //   {
    //     id: "r315_psr_attendance_secondary_user",
    //     slug: "r315_psr_attendance_secondary_user",
    //     title: "R315 - PSR Attendance [Secondary User]",
    //     text: "r315_psr_attendance_secondary_user",
    //     navLink: "/r315_psr_attendance_secondary_user",
    //   },
    //   {
    //     id: "r316_market_visit_summary_detail",
    //     slug: "r316_market_visit_summary_detail",
    //     title: "R316 - Market Visit Summary [Detail]",
    //     text: "r316_market_visit_summary_detail",
    //     navLink: "/r316_market_visit_summary_detail",
    //   },
    //   {
    //     id: "r317_morning_gate_meeting",
    //     slug: "r317_morning_gate_meeting",
    //     title: "R317 - Morning Gate Meeting",
    //     text: "r317_morning_gate_meeting",
    //     navLink: "/r317_morning_gate_meeting",
    //   },
    //   {
    //     id: "r318_orderbooking_status_mde",
    //     slug: "r318_orderbooking_status_mde",
    //     title: "R318 - Orderbooking Status [MDE]",
    //     text: "r318_orderbooking_status_mde",
    //     navLink: "/r318_orderbooking_status_mde",
    //   },
    //   {
    //     id: "r319_retailer_orders",
    //     slug: "r319_retailer_orders",
    //     title: "R319 - Retailer Orders",
    //     text: "r319_retailer_orders",
    //     navLink: "/r319_retailer_orders",
    //   },
    //   {
    //     id: "r320_pjp_kpi",
    //     slug: "r320_pjp_kpi",
    //     title: "R320 - PJP KPI",
    //     text: "r320_pjp_kpi",
    //     navLink: "/r320_pjp_kpi",
    //   },
    //   {
    //     id: "r321_transfer_note_summary",
    //     slug: "r321_transfer_note_summary",
    //     title: "R321 - Transfer Note Summary",
    //     text: "r321_transfer_note_summary",
    //     navLink: "/r321_transfer_note_summary",
    //   },
    //   {
    //     id: "r327_warehouse_transfer_summary",
    //     slug: "r327_warehouse_transfer_summary",
    //     title: "R327 - Warehouse Transfer Summary",
    //     text: "r327_warehouse_transfer_summary",
    //     navLink: "/r327_warehouse_transfer_summary",
    //   },
    //   {
    //     id: "r322_dispatch_report",
    //     slug: "r322_dispatch_report",
    //     title: "R322 - Dispatch Report",
    //     text: "r322_dispatch_report",
    //     navLink: "/r322_dispatch_report",
    //   },
    //   {
    //     id: "r323_survey_auto",
    //     slug: "r323_survey_auto",
    //     title: "R323 - Survey Auto",
    //     text: "r323_survey_auto",
    //     navLink: "/r323_survey_auto",
    //   },
    //   {
    //     id: "r324_cooler_issuance",
    //     slug: "r324_cooler_issuance",
    //     title: "R324 - Cooler Issuance",
    //     text: "r324_cooler_issuance",
    //     navLink: "/r324_cooler_issuance",
    //   },
    //   {
    //     id: "r325_outlet_kpi_report",
    //     slug: "r325_outlet_kpi_report",
    //     title: "R325 - Outlet KPI Report",
    //     text: "r325_outlet_kpi_report",
    //     navLink: "/r325_outlet_kpi_report",
    //   },
    //   {
    //     id: "r326_warehouse_stock",
    //     slug: "r326_warehouse_stock",
    //     title: "R326 - Warehouse Stock",
    //     text: "r326_warehouse_stock",
    //     navLink: "/r326_warehouse_stock",
    //   },
    //   {
    //     id: "r331_warehouse_summary",
    //     slug: "r331_warehouse_summary",
    //     title: "R331 - Warehouse Summary",
    //     text: "r331_warehouse_summary",
    //     navLink: "/r331_warehouse_summary",
    //   },
    //   {
    //     id: "r810_election_survey_report",
    //     slug: "r810_election_survey_report",
    //     title: "R810 - Election Survey Report",
    //     text: "r810_election_survey_report",
    //     navLink: "/r810_election_survey_report",
    //   },
    //   {
    //     id: "r332_warehouse_tracker_report",
    //     slug: "r332_warehouse_tracker_report",
    //     title: "R332 - Warehouse Tracker Report",
    //     text: "r332_warehouse_tracker_report",
    //     navLink: "/r332_warehouse_tracker_report",
    //   },
    //   {
    //     id: "r333_warehouse_net_stock",
    //     slug: "r333_warehouse_net_stock",
    //     title: "R333 - Warehouse Net Stock",
    //     text: "r333_warehouse_net_stock",
    //     navLink: "/r333_warehouse_net_stock",
    //   },
    //   {
    //     id: "r490_mem_tickets_assignment",
    //     slug: "r490_mem_tickets_assignment",
    //     title: "R490 - MEM Tickets Assignment",
    //     text: "r490_mem_tickets_assignment",
    //     navLink: "/r490_mem_tickets_assignment",
    //   },
    // ],
  },
  {
    id: "crm",
    slug: "crm",
    title: "CRM",
    icon: () => Settings,
    navLink: "/crm",

    // children: [
    //   {
    //     id: "complaint",
    //     slug: "complaint",
    //     title: "Complaint",
    //     text: "complaint",
    //     navLink: "/complaint",
    //   },
    //   {
    //     id: "complaint_assignment",
    //     slug: "complaint_assignment",
    //     title: "Complaint Assignment",
    //     text: "complaint_assignment",
    //     navLink: "/complaint_assignment",
    //   },
    //   {
    //     id: "complaint_verification",
    //     slug: "complaint_verification",
    //     title: "Complaint Verification",
    //     text: "complaint_verification",
    //     navLink: "/complaint_verification",
    //   },
    //   {
    //     id: "resolve_complaint",
    //     slug: "resolve_complaint",
    //     title: "Resolve Complaint",
    //     text: "resolve_complaint",
    //     navLink: "/resolve_complaint",
    //   },
    //   {
    //     id: "complaint_forwarding",
    //     slug: "complaint_forwarding",
    //     title: "Complaint Forwarding",
    //     text: "complaint_forwarding",
    //     navLink: "/complaint_forwarding",
    //   },
    //   {
    //     id: "resolve_complaint_new",
    //     slug: "resolve_complaint_new",
    //     title: "Resolve Complaint (New)",
    //     text: "resolve_complaint_new",
    //     navLink: "/resolve_complaint_new",
    //   },
    //   {
    //     id: "crm_helpdesk",
    //     slug: "crm_helpdesk",
    //     title: "CRM Helpdesk",
    //     text: "crm_helpdesk",
    //     navLink: "/crm_helpdesk",
    //   },
    // ],
  },
  {
    id: "distributor_reports",
    slug: "distributor_reports",
    title: "Distributor Reports",
    icon: () => pinMapIcon,
    navLink: "/distributor_reports",

    // children: [
    //   {
    //     id: "activity_summary",
    //     slug: "activity_summary",
    //     title: "Activity Summary",
    //     text: "activity_summary",
    //     navLink: "/activity_summary",
    //   },
    //   {
    //     id: "stock_summary",
    //     slug: "stock_summary",
    //     title: "Stock Summary",
    //     text: "stock_summary",
    //     navLink: "/stock_summary",
    //   },
    //   {
    //     id: "sales_activity",
    //     slug: "sales_activity",
    //     title: "Sales Activity",
    //     text: "sales_activity",
    //     navLink: "/sales_activity",
    //   },
    //   {
    //     id: "adjusted_sales_summary",
    //     slug: "adjusted_sales_summary",
    //     title: "Adjusted Sales Summary",
    //     text: "adjusted_sales_summary",
    //     navLink: "/adjusted_sales_summary",
    //   },
    //   {
    //     id: "dispatch_summary",
    //     slug: "dispatch_summary",
    //     title: "Dispatch Summary",
    //     text: "dispatch_summary",
    //     navLink: "/dispatch_summary",
    //   },
    //   {
    //     id: "outlet_list",
    //     slug: "outlet_list",
    //     title: "Outlet List",
    //     text: "outlet_list",
    //     navLink: "/outlet_list",
    //   },
    //   {
    //     id: "converted_sales",
    //     slug: "converted_sales",
    //     title: "Converted Sales",
    //     text: "converted_sales",
    //     navLink: "/converted_sales",
    //   },
    // ],
  },
  {
    id: "mobile",
    slug: "mobile",
    title: "Mobile",
    icon: () => mobileIcon,
    navLink: "/mobile",

    // children: [
    //   {
    //     id: "CensusListOnline",
    //     slug: "CensusListOnline",
    //     title: "Census List Online",
    //     text: "Census List Online",
    //     navLink: "/CensusListOnline",
    //     // icon: () => YourIconComponent, // You can add the icon if needed
    //   },
    //   {
    //     id: "CreateOrder",
    //     slug: "CreateOrder",
    //     title: "Create Order",
    //     text: "Create Order",
    //     navLink: "/CreateOrder",
    //     // icon: () => YourIconComponent,
    //   },
    //   {
    //     id: "CreateOrderAllOutlets",
    //     slug: "CreateOrderAllOutlets",
    //     title: "Create Order [All Outlets]",
    //     text: "Create Order [All Outlets]",
    //     navLink: "/CreateOrderAllOutlets",
    //     // icon: () => YourIconComponent,
    //   },
    //   {
    //     id: "OrderList",
    //     slug: "OrderList",
    //     title: "Order List",
    //     text: "Order List",
    //     navLink: "/OrderList",
    //     // icon: () => YourIconComponent,
    //   },
    //   {
    //     id: "OrderSummary",
    //     slug: "OrderSummary",
    //     title: "Order Summary",
    //     text: "Order Summary",
    //     navLink: "/OrderSummary",
    //     // icon: () => YourIconComponent,
    //   },
    //   {
    //     id: "Synchronize",
    //     slug: "Synchronize",
    //     title: "Synchronize",
    //     text: "Synchronize",
    //     navLink: "/Synchronize",
    //     // icon: () => YourIconComponent,
    //   },
    //   {
    //     id: "ReportCenter",
    //     slug: "ReportCenter",
    //     title: "Report Center",
    //     text: "Report Center",
    //     navLink: "/ReportCenter",
    //     // icon: () => YourIconComponent,
    //   },
    //   {
    //     id: "Complaint",
    //     slug: "Complaint",
    //     title: "Complaint",
    //     text: "Complaint",
    //     navLink: "/Complaint",
    //     // icon: () => YourIconComponent,
    //   },
    // ],
  },
  {
    id: "cash",
    slug: "Cash",
    title: "Cash",
    icon: () => CashIcon,
    navLink: "/cash",

    // children: [
    //   {
    //     id: "CashReceipt",
    //     slug: "CashReceipt",
    //     title: "Cash Receipt",
    //     text: "Cash Receipt",
    //     navLink: "/CashReceipt",
    //     // icon: () => YourIconComponent, // You can add the icon if needed
    //   },
    //   {
    //     id: "CashPayment",
    //     slug: "CashPayment",
    //     title: "Cash Payment",
    //     text: "Cash Payment",
    //     navLink: "/CashPayment",
    //     // icon: () => YourIconComponent,
    //   },
    //   {
    //     id: "ChequeReturn",
    //     slug: "ChequeReturn",
    //     title: "Cheque Return",
    //     text: "Cheque Return",
    //     navLink: "/ChequeReturn",
    //     // icon: () => YourIconComponent,
    //   },
    //   {
    //     id: "DirectDebit",
    //     slug: "DirectDebit",
    //     title: "Direct Debit",
    //     text: "Direct Debit",
    //     navLink: "/DirectDebit",
    //     // icon: () => YourIconComponent,
    //   },
    //   {
    //     id: "InvoicePosting",
    //     slug: "InvoicePosting",
    //     title: "Invoice Posting",
    //     text: "Invoice Posting",
    //     navLink: "/InvoicePosting",
    //     // icon: () => YourIconComponent,
    //   },
    //   {
    //     id: "OneTimeCredit",
    //     slug: "OneTimeCredit",
    //     title: "One Time Credit",
    //     text: "One Time Credit",
    //     navLink: "/OneTimeCredit",
    //     // icon: () => YourIconComponent,
    //   },
    //   {
    //     id: "AdjustedInvoicePosting",
    //     slug: "AdjustedInvoicePosting",
    //     title: "Adjusted Invoice Posting",
    //     text: "Adjusted Invoice Posting",
    //     navLink: "/AdjustedInvoicePosting",
    //     // icon: () => YourIconComponent,
    //   },
    //   {
    //     id: "OpeningBalances",
    //     slug: "OpeningBalances",
    //     title: "Opening Balances",
    //     text: "Opening Balances",
    //     navLink: "/OpeningBalances",
    //     // icon: () => YourIconComponent,
    //   },
    //   {
    //     id: "UnpostInvoice",
    //     slug: "UnpostInvoice",
    //     title: "Unpost Invoice",
    //     text: "Unpost Invoice",
    //     navLink: "/UnpostInvoice",
    //     // icon: () => YourIconComponent,
    //   },
    //   {
    //     id: "OrderStatus",
    //     slug: "OrderStatus",
    //     title: "Order Status",
    //     text: "Order Status",
    //     navLink: "/OrderStatus",
    //     // icon: () => YourIconComponent,
    //   },
    //   {
    //     id: "UnpostCashReceipt",
    //     slug: "UnpostCashReceipt",
    //     title: "Unpost Cash Receipt",
    //     text: "Unpost Cash Receipt",
    //     navLink: "/UnpostCashReceipt",
    //     // icon: () => YourIconComponent,
    //   },
    //   {
    //     id: "InterLedgerTransfer",
    //     slug: "InterLedgerTransfer",
    //     title: "Inter-Ledger Transfer",
    //     text: "Inter-Ledger Transfer",
    //     navLink: "/InterLedgerTransfer",
    //     // icon: () => YourIconComponent,
    //   },
    //   {
    //     id: "CustomerBalance",
    //     slug: "CustomerBalance",
    //     title: "Customer Balance",
    //     text: "Customer Balance",
    //     navLink: "/CustomerBalance",
    //     // icon: () => YourIconComponent,
    //   },
    //   {
    //     id: "AccountAdjustment",
    //     slug: "AccountAdjustment",
    //     title: "Account Adjustment",
    //     text: "Account Adjustment",
    //     navLink: "/AccountAdjustment",
    //     // icon: () => YourIconComponent,
    //   },
    //   {
    //     id: "OrderPosting",
    //     slug: "OrderPosting",
    //     title: "Order Posting",
    //     text: "Order Posting",
    //     navLink: "/OrderPosting",
    //     // icon: () => YourIconComponent,
    //   },
    //   {
    //     id: "UnpostOrder",
    //     slug: "UnpostOrder",
    //     title: "Unpost Order",
    //     text: "Unpost Order",
    //     navLink: "/UnpostOrder",
    //     // icon: () => YourIconComponent,
    //   },
    //   {
    //     id: "CreditLimitRequest",
    //     slug: "CreditLimitRequest",
    //     title: "Credit Limit Request",
    //     text: "Credit Limit Request",
    //     navLink: "/CreditLimitRequest",
    //     // icon: () => YourIconComponent,
    //   },
    //   {
    //     id: "SalesReturnPosting",
    //     slug: "SalesReturnPosting",
    //     title: "Sales Return Posting",
    //     text: "Sales Return Posting",
    //     navLink: "/SalesReturnPosting",
    //     // icon: () => YourIconComponent,
    //   },
    //   {
    //     id: "SalesReturnUnPosting",
    //     slug: "SalesReturnUnPosting",
    //     title: "Sales Return UnPosting",
    //     text: "Sales Return UnPosting",
    //     navLink: "/SalesReturnUnPosting",
    //     // icon: () => YourIconComponent,
    //   },
    //   {
    //     id: "DeactivateCreditLimit",
    //     slug: "DeactivateCreditLimit",
    //     title: "Deactivate Credit Limit",
    //     text: "Deactivate Credit Limit",
    //     navLink: "/DeactivateCreditLimit",
    //     // icon: () => YourIconComponent,
    //   },
    // ],
  },
];

export default navigationLinks;
